-- Add comprehensive translations for Shop, About, Contact, Auth and all other pages
INSERT INTO public.translations (language_code, translation_key, translation_value, context) VALUES

-- English shop page translations
('en', 'shop.browse_products', 'Browse Products', 'shop'),
('en', 'shop.discover_verified', 'Discover verified products from trusted vendors', 'shop'),
('en', 'shop.search.title', 'Search', 'shop'),
('en', 'shop.search.placeholder', 'Search products...', 'shop'),
('en', 'shop.category.title', 'Category', 'shop'),
('en', 'shop.category.all', 'All Categories', 'shop'),
('en', 'shop.price_range', 'Price Range (BTC)', 'shop'),
('en', 'shop.sort.title', 'Sort By', 'shop'),
('en', 'shop.sort.newest', 'Newest First', 'shop'),
('en', 'shop.sort.oldest', 'Oldest First', 'shop'),
('en', 'shop.sort.price_low', 'Price: Low to High', 'shop'),
('en', 'shop.sort.price_high', 'Price: High to Low', 'shop'),
('en', 'shop.sort.popular', 'Most Popular', 'shop'),
('en', 'shop.top_vendors', 'Top Vendors', 'shop'),

-- English about page translations
('en', 'about.title', 'About OpesMarket', 'about'),
('en', 'about.subtitle', 'The premier AI-powered anonymous marketplace for secure Bitcoin transactions', 'about'),
('en', 'about.mission.title', 'Our Mission', 'about'),
('en', 'about.mission.text', 'OpesMarket is revolutionizing online commerce by providing the world''s most secure, private, and intelligent marketplace. We believe in true digital freedom where privacy is paramount, transactions are transparent, and trust is built through cutting-edge AI technology rather than compromising personal data.', 'about'),
('en', 'about.feature.bitcoin_only', 'Bitcoin-Only', 'about'),
('en', 'about.feature.bitcoin_desc', 'Fully decentralized payments using only Bitcoin, ensuring true financial sovereignty and privacy.', 'about'),
('en', 'about.feature.security', 'Military-Grade Security', 'about'),
('en', 'about.feature.security_desc', 'Advanced encryption, multi-signature escrow, and AI-powered fraud detection protect every transaction.', 'about'),
('en', 'about.feature.privacy', 'Complete Privacy', 'about'),
('en', 'about.feature.privacy_desc', 'Zero personal data collection with anonymous browsing and PGP-encrypted communications.', 'about'),
('en', 'about.feature.community', 'Trusted Community', 'about'),
('en', 'about.feature.community_desc', 'Verified vendors with reputation-based trust scores and transparent community feedback.', 'about'),
('en', 'about.feature.ai', 'AI-Powered Intelligence', 'about'),
('en', 'about.feature.ai_desc', 'Smart recommendations, automated security monitoring, and intelligent dispute resolution.', 'about'),
('en', 'about.feature.global', 'Global Accessibility', 'about'),
('en', 'about.feature.global_desc', 'Available worldwide with multilingual support and seamless cross-border transactions.', 'about'),
('en', 'about.values.title', 'Our Values', 'about'),
('en', 'about.values.privacy', 'Privacy First', 'about'),
('en', 'about.values.privacy_desc', 'Your privacy is non-negotiable. We never collect personal data and ensure complete anonymity.', 'about'),
('en', 'about.values.trust', 'Trust & Safety', 'about'),
('en', 'about.values.trust_desc', 'Building trust through transparency, verified vendors, and AI-powered security measures.', 'about'),
('en', 'about.values.innovation', 'Innovation', 'about'),
('en', 'about.values.innovation_desc', 'Continuously improving with cutting-edge technology and user-centered design.', 'about'),

-- English contact page translations
('en', 'contact.title', 'Contact OpesMarket', 'contact'),
('en', 'contact.subtitle', 'Get secure support for all your marketplace needs', 'contact'),
('en', 'contact.form.title', 'Secure Contact Form', 'contact'),
('en', 'contact.form.subject', 'Subject', 'contact'),
('en', 'contact.form.subject_placeholder', 'Brief description of your inquiry', 'contact'),
('en', 'contact.form.priority', 'Priority Level', 'contact'),
('en', 'contact.form.priority.low', 'Low - General inquiry', 'contact'),
('en', 'contact.form.priority.normal', 'Normal - Standard support', 'contact'),
('en', 'contact.form.priority.high', 'High - Technical issue', 'contact'),
('en', 'contact.form.priority.urgent', 'Urgent - Security concern', 'contact'),
('en', 'contact.form.message', 'Message', 'contact'),
('en', 'contact.form.message_placeholder', 'Please provide detailed information about your inquiry or issue...', 'contact'),
('en', 'contact.form.send', 'Send Secure Message', 'contact'),
('en', 'contact.response_times.title', 'Response Times', 'contact'),
('en', 'contact.response_times.general', 'General Inquiries', 'contact'),
('en', 'contact.response_times.technical', 'Technical Support', 'contact'),
('en', 'contact.response_times.security', 'Security Issues', 'contact'),
('en', 'contact.response_times.urgent', 'Urgent Matters', 'contact'),
('en', 'contact.topics.title', 'Common Topics', 'contact'),
('en', 'contact.topics.bitcoin', 'Bitcoin Payment Issues', 'contact'),
('en', 'contact.topics.verification', 'Vendor Verification', 'contact'),
('en', 'contact.topics.disputes', 'Order Disputes', 'contact'),
('en', 'contact.topics.technical', 'Technical Support', 'contact'),
('en', 'contact.security.title', 'Security Notice', 'contact'),
('en', 'contact.security.text', 'All communications are encrypted end-to-end. We never ask for passwords, private keys, or sensitive information via support channels.', 'contact'),
('en', 'contact.pgp.title', 'Secure Communication', 'contact'),
('en', 'contact.pgp.subtitle', 'For maximum security and privacy, encrypt your communications using our PGP public key.', 'contact'),
('en', 'contact.pgp.key_title', 'OpesMarket PGP Public Key', 'contact'),
('en', 'contact.pgp.alert', 'Use this PGP key to encrypt sensitive communications. Always verify the key fingerprint before use.', 'contact'),
('en', 'contact.pgp.copy', 'Copy Key', 'contact'),
('en', 'contact.pgp.copied', 'Copied!', 'contact'),
('en', 'contact.pgp.how_to_title', 'How to use this key:', 'contact'),

-- English auth page translations
('en', 'auth.title', 'OpesMarket', 'auth'),
('en', 'auth.subtitle', 'Secure Anonymous Marketplace', 'auth'),
('en', 'auth.login.title', 'Welcome Back', 'auth'),
('en', 'auth.login.description', 'Enter your credentials to access your account', 'auth'),
('en', 'auth.login.email', 'Email', 'auth'),
('en', 'auth.login.password', 'Password', 'auth'),
('en', 'auth.login.submit', 'Sign In', 'auth'),
('en', 'auth.signup.title', 'Create Account', 'auth'),
('en', 'auth.signup.description', 'Join the secure marketplace', 'auth'),
('en', 'auth.signup.display_name', 'Display Name', 'auth'),
('en', 'auth.signup.email', 'Email', 'auth'),
('en', 'auth.signup.account_type', 'Account Type', 'auth'),
('en', 'auth.signup.buyer', 'Buyer', 'auth'),
('en', 'auth.signup.vendor', 'Vendor', 'auth'),
('en', 'auth.signup.password', 'Password', 'auth'),
('en', 'auth.signup.confirm_password', 'Confirm Password', 'auth'),
('en', 'auth.signup.submit', 'Create Account', 'auth'),
('en', 'auth.tabs.login', 'Login', 'auth'),
('en', 'auth.tabs.signup', 'Sign Up', 'auth')

ON CONFLICT (language_code, translation_key, context) DO UPDATE SET 
  translation_value = EXCLUDED.translation_value;