-- Create basic translations for key UI elements
INSERT INTO public.translations (language_code, translation_key, translation_value, context) VALUES
-- English translations
('en', 'hero.title.ai_powered', 'AI-Powered', 'hero'),
('en', 'hero.title.anonymous_marketplace', 'Anonymous Marketplace', 'hero'),
('en', 'hero.subtitle', 'Trade securely with Bitcoin-only transactions, verified vendors, and AI-driven trust scoring. Your privacy is our priority.', 'hero'),
('en', 'hero.cta.start_shopping', 'Start Shopping', 'hero'),
('en', 'hero.cta.become_vendor', 'Become a Vendor', 'hero'),
('en', 'hero.feature.bitcoin_only', 'Bitcoin Only', 'hero'),
('en', 'hero.feature.bitcoin_desc', 'Secure, private transactions with built-in escrow', 'hero'),
('en', 'hero.feature.verified_vendors', 'Verified Vendors', 'hero'),
('en', 'hero.feature.verified_desc', '$250 annual bond ensures quality and accountability', 'hero'),
('en', 'hero.feature.ai_powered', 'AI-Powered', 'hero'),
('en', 'hero.feature.ai_desc', 'Smart fraud detection and dynamic trust scoring', 'hero'),
('en', 'hero.feature.anonymous', 'Anonymous', 'hero'),
('en', 'hero.feature.anonymous_desc', 'End-to-end encryption with optional Tor support', 'hero'),
('en', 'nav.shop', 'Shop', 'nav'),
('en', 'nav.login', 'Login', 'nav'),
('en', 'nav.logout', 'Logout', 'nav'),
('en', 'nav.become_vendor', 'Become Vendor', 'nav'),

-- Spanish translations
('es', 'hero.title.ai_powered', 'Impulsado por IA', 'hero'),
('es', 'hero.title.anonymous_marketplace', 'Mercado Anónimo', 'hero'),
('es', 'hero.subtitle', 'Comercia de forma segura con transacciones solo en Bitcoin, vendedores verificados y puntuación de confianza impulsada por IA. Tu privacidad es nuestra prioridad.', 'hero'),
('es', 'hero.cta.start_shopping', 'Empezar a Comprar', 'hero'),
('es', 'hero.cta.become_vendor', 'Convertirse en Vendedor', 'hero'),
('es', 'hero.feature.bitcoin_only', 'Solo Bitcoin', 'hero'),
('es', 'hero.feature.bitcoin_desc', 'Transacciones seguras y privadas con depósito en garantía incorporado', 'hero'),
('es', 'hero.feature.verified_vendors', 'Vendedores Verificados', 'hero'),
('es', 'hero.feature.verified_desc', 'Fianza anual de $250 garantiza calidad y responsabilidad', 'hero'),
('es', 'hero.feature.ai_powered', 'Impulsado por IA', 'hero'),
('es', 'hero.feature.ai_desc', 'Detección inteligente de fraudes y puntuación dinámica de confianza', 'hero'),
('es', 'hero.feature.anonymous', 'Anónimo', 'hero'),
('es', 'hero.feature.anonymous_desc', 'Cifrado de extremo a extremo con soporte opcional de Tor', 'hero'),
('es', 'nav.shop', 'Tienda', 'nav'),
('es', 'nav.login', 'Iniciar Sesión', 'nav'),
('es', 'nav.logout', 'Cerrar Sesión', 'nav'),
('es', 'nav.become_vendor', 'Ser Vendedor', 'nav'),

-- French translations
('fr', 'hero.title.ai_powered', 'Alimenté par l''IA', 'hero'),
('fr', 'hero.title.anonymous_marketplace', 'Marché Anonyme', 'hero'),
('fr', 'hero.subtitle', 'Commercez en sécurité avec des transactions Bitcoin uniquement, des vendeurs vérifiés et un scoring de confiance basé sur l''IA. Votre vie privée est notre priorité.', 'hero'),
('fr', 'hero.cta.start_shopping', 'Commencer à Acheter', 'hero'),
('fr', 'hero.cta.become_vendor', 'Devenir Vendeur', 'hero'),
('fr', 'hero.feature.bitcoin_only', 'Bitcoin Seulement', 'hero'),
('fr', 'hero.feature.bitcoin_desc', 'Transactions sécurisées et privées avec dépôt de garantie intégré', 'hero'),
('fr', 'hero.feature.verified_vendors', 'Vendeurs Vérifiés', 'hero'),
('fr', 'hero.feature.verified_desc', 'Caution annuelle de 250$ garantit qualité et responsabilité', 'hero'),
('fr', 'hero.feature.ai_powered', 'Alimenté par l''IA', 'hero'),
('fr', 'hero.feature.ai_desc', 'Détection intelligente de fraude et scoring de confiance dynamique', 'hero'),
('fr', 'hero.feature.anonymous', 'Anonyme', 'hero'),
('fr', 'hero.feature.anonymous_desc', 'Chiffrement de bout en bout avec support Tor optionnel', 'hero'),
('fr', 'nav.shop', 'Boutique', 'nav'),
('fr', 'nav.login', 'Connexion', 'nav'),
('fr', 'nav.logout', 'Déconnexion', 'nav'),
('fr', 'nav.become_vendor', 'Devenir Vendeur', 'nav');