-- Complete multilingual translation system for OpesMarket
-- This migration adds ALL translations for 10 languages

-- Delete existing incomplete translations
DELETE FROM public.translations;

-- Insert comprehensive translations for all languages
INSERT INTO public.translations (language_code, translation_key, translation_value, context) VALUES

-- English translations
('en', 'nav.search', 'Search products, vendors...', 'navigation'),
('en', 'nav.shop', 'Shop', 'navigation'),
('en', 'nav.forum', 'Forum', 'navigation'),
('en', 'nav.wishlist', 'Wishlist', 'navigation'),
('en', 'nav.affiliate', 'Affiliate', 'navigation'),
('en', 'nav.orders', 'My Orders', 'navigation'),
('en', 'nav.messages', 'Messages', 'navigation'),
('en', 'nav.profile', 'Profile', 'navigation'),
('en', 'nav.become_vendor', 'Become a Vendor', 'navigation'),
('en', 'nav.logout', 'Logout', 'navigation'),
('en', 'nav.login', 'Login', 'navigation'),

('en', 'hero.title.ai_powered', 'AI-Powered', 'hero'),
('en', 'hero.title.anonymous_marketplace', 'Anonymous Marketplace', 'hero'),
('en', 'hero.subtitle', 'Trade securely with Bitcoin-only transactions, verified vendors, and AI-driven trust scoring.', 'hero'),
('en', 'hero.cta.start_shopping', 'Start Shopping', 'hero'),
('en', 'hero.cta.become_vendor', 'Become a Vendor', 'hero'),
('en', 'hero.feature.bitcoin_only', 'Bitcoin Only', 'hero'),
('en', 'hero.feature.bitcoin_desc', 'Fully decentralized payments using only Bitcoin for true financial freedom.', 'hero'),
('en', 'hero.feature.verified_vendors', 'Verified Vendors', 'hero'),
('en', 'hero.feature.verified_desc', 'AI-verified sellers with transparent reputation and trust scoring systems.', 'hero'),
('en', 'hero.feature.ai_powered', 'AI-Powered', 'hero'),
('en', 'hero.feature.ai_desc', 'Smart recommendations and automated security for the best experience.', 'hero'),
('en', 'hero.feature.anonymous', 'Anonymous', 'hero'),
('en', 'hero.feature.anonymous_desc', 'Complete privacy with no personal data collection or tracking.', 'hero'),

('en', 'featured_vendors.title', 'Featured Vendors', 'vendors'),
('en', 'featured_vendors.subtitle', 'Discover top-rated, verified vendors in our secure marketplace', 'vendors'),
('en', 'featured_vendors.view_all', 'View All Vendors', 'vendors'),

('en', 'footer.description', 'The world''s most secure anonymous marketplace. Trade with confidence using Bitcoin, verified vendors, and AI-powered security systems.', 'footer'),
('en', 'footer.encrypted', 'End-to-End Encrypted', 'footer'),
('en', 'footer.ai_powered', 'AI-Powered', 'footer'),
('en', 'footer.menu.marketplace', 'Marketplace', 'footer'),
('en', 'footer.menu.browse_products', 'Browse Products', 'footer'),
('en', 'footer.menu.verified_vendors', 'Verified Vendors', 'footer'),
('en', 'footer.menu.how_to_order', 'How to Order', 'footer'),
('en', 'footer.menu.selling_guide', 'Selling Guide', 'footer'),
('en', 'footer.menu.escrow_security', 'Escrow Security', 'footer'),
('en', 'footer.menu.categories', 'Categories', 'footer'),
('en', 'footer.menu.support', 'Support', 'footer'),
('en', 'footer.menu.faq', 'FAQ', 'footer'),
('en', 'footer.menu.about_us', 'About Us', 'footer'),
('en', 'footer.menu.contact', 'Contact', 'footer'),
('en', 'footer.menu.forbidden', 'Safety & Terms', 'footer'),
('en', 'footer.menu.pgp_tools', 'PGP Tools', 'footer'),
('en', 'footer.menu.help_center', 'Help Center', 'footer'),
('en', 'footer.copyright', '© 2024 OpesMarket. Secure, Anonymous, Decentralized.', 'footer'),
('en', 'footer.status.secure', 'Secure & Online', 'footer'),
('en', 'footer.status.online', '24/7 Available', 'footer'),

('en', 'about.title', 'About OpesMarket', 'about'),
('en', 'about.subtitle', 'The premier AI-powered anonymous marketplace for secure Bitcoin transactions', 'about'),
('en', 'about.mission.title', 'Our Mission', 'about'),
('en', 'about.mission.content', 'OpesMarket is revolutionizing online commerce by providing the world''s most secure, private, and intelligent marketplace. We believe in true digital freedom where privacy is paramount, transactions are transparent, and trust is built through cutting-edge AI technology rather than compromising personal data.', 'about'),
('en', 'about.features.bitcoin.title', 'Bitcoin-Only', 'about'),
('en', 'about.features.bitcoin.desc', 'Fully decentralized payments using only Bitcoin, ensuring true financial sovereignty and privacy.', 'about'),
('en', 'about.features.security.title', 'Military-Grade Security', 'about'),
('en', 'about.features.security.desc', 'Advanced encryption, multi-signature escrow, and AI-powered fraud detection protect every transaction.', 'about'),
('en', 'about.features.privacy.title', 'Complete Privacy', 'about'),
('en', 'about.features.privacy.desc', 'Zero personal data collection with anonymous browsing and PGP-encrypted communications.', 'about'),
('en', 'about.features.community.title', 'Trusted Community', 'about'),
('en', 'about.features.community.desc', 'Verified vendors with reputation-based trust scores and transparent community feedback.', 'about'),
('en', 'about.features.ai.title', 'AI-Powered Intelligence', 'about'),
('en', 'about.features.ai.desc', 'Smart recommendations, automated security monitoring, and intelligent dispute resolution.', 'about'),
('en', 'about.features.global.title', 'Global Accessibility', 'about'),
('en', 'about.features.global.desc', 'Available worldwide with multilingual support and seamless cross-border transactions.', 'about'),

('en', 'contact.title', 'Contact OpesMarket', 'contact'),
('en', 'contact.subtitle', 'Get in touch with our team for support, questions, or partnership inquiries. All communications are encrypted and secure.', 'contact'),
('en', 'contact.form.title', 'Secure Contact Form', 'contact'),
('en', 'contact.form.subject', 'Subject', 'contact'),
('en', 'contact.form.subject_placeholder', 'Brief description of your inquiry', 'contact'),
('en', 'contact.form.urgency', 'Priority Level', 'contact'),
('en', 'contact.form.urgency.low', 'Low - General inquiry', 'contact'),
('en', 'contact.form.urgency.normal', 'Normal - Standard support', 'contact'),
('en', 'contact.form.urgency.high', 'High - Technical issue', 'contact'),
('en', 'contact.form.urgency.urgent', 'Urgent - Security concern', 'contact'),
('en', 'contact.form.message', 'Message', 'contact'),
('en', 'contact.form.message_placeholder', 'Please provide detailed information about your inquiry or issue...', 'contact'),
('en', 'contact.form.send', 'Send Secure Message', 'contact'),
('en', 'contact.success.title', 'Message Sent', 'contact'),
('en', 'contact.success.description', 'Your secure message has been received. We will respond within 24 hours.', 'contact'),
('en', 'contact.response.title', 'Response Times', 'contact'),
('en', 'contact.response.general', 'General Inquiries', 'contact'),
('en', 'contact.response.technical', 'Technical Support', 'contact'),
('en', 'contact.response.security', 'Security Issues', 'contact'),
('en', 'contact.response.urgent', 'Urgent Matters', 'contact'),
('en', 'contact.topics.title', 'Common Topics', 'contact'),
('en', 'contact.security.title', 'Security Notice', 'contact'),
('en', 'contact.security.description', 'All communications are encrypted end-to-end. We never ask for passwords, private keys, or sensitive information via support channels.', 'contact'),

('en', 'shop.title', 'Browse Products', 'shop'),
('en', 'shop.search.placeholder', 'Discover verified products from trusted vendors', 'shop'),
('en', 'shop.filters.category', 'Category', 'shop'),
('en', 'shop.filters.all_categories', 'All Categories', 'shop'),
('en', 'shop.filters.price_range', 'Price Range (BTC)', 'shop'),
('en', 'shop.filters.sort_by', 'Sort By', 'shop'),
('en', 'shop.filters.newest', 'Newest First', 'shop'),
('en', 'shop.filters.price_low', 'Price: Low to High', 'shop'),
('en', 'shop.filters.price_high', 'Price: High to Low', 'shop'),
('en', 'shop.filters.rating', 'Most Popular', 'shop'),
('en', 'shop.top_vendors.title', 'Top Vendors', 'shop'),

('en', 'ui.search', 'Search', 'ui'),
('en', 'vendor.verified', 'Verified Vendors', 'vendor'),

-- Spanish translations
('es', 'nav.search', 'Buscar productos, vendedores...', 'navigation'),
('es', 'nav.shop', 'Tienda', 'navigation'),
('es', 'nav.forum', 'Foro', 'navigation'),
('es', 'nav.wishlist', 'Lista de Deseos', 'navigation'),
('es', 'nav.affiliate', 'Afiliado', 'navigation'),
('es', 'nav.orders', 'Mis Pedidos', 'navigation'),
('es', 'nav.messages', 'Mensajes', 'navigation'),
('es', 'nav.profile', 'Perfil', 'navigation'),
('es', 'nav.become_vendor', 'Convertirse en Vendedor', 'navigation'),
('es', 'nav.logout', 'Cerrar Sesión', 'navigation'),
('es', 'nav.login', 'Iniciar Sesión', 'navigation'),

('es', 'hero.title.ai_powered', 'Impulsado por IA', 'hero'),
('es', 'hero.title.anonymous_marketplace', 'Mercado Anónimo', 'hero'),
('es', 'hero.subtitle', 'Comercia de forma segura con transacciones solo en Bitcoin, vendedores verificados y puntuación de confianza impulsada por IA.', 'hero'),
('es', 'hero.cta.start_shopping', 'Comenzar a Comprar', 'hero'),
('es', 'hero.cta.become_vendor', 'Convertirse en Vendedor', 'hero'),
('es', 'hero.feature.bitcoin_only', 'Solo Bitcoin', 'hero'),
('es', 'hero.feature.bitcoin_desc', 'Pagos completamente descentralizados usando solo Bitcoin para verdadera libertad financiera.', 'hero'),
('es', 'hero.feature.verified_vendors', 'Vendedores Verificados', 'hero'),
('es', 'hero.feature.verified_desc', 'Vendedores verificados por IA con sistemas transparentes de reputación y puntuación de confianza.', 'hero'),
('es', 'hero.feature.ai_powered', 'Impulsado por IA', 'hero'),
('es', 'hero.feature.ai_desc', 'Recomendaciones inteligentes y seguridad automatizada para la mejor experiencia.', 'hero'),
('es', 'hero.feature.anonymous', 'Anónimo', 'hero'),
('es', 'hero.feature.anonymous_desc', 'Privacidad completa sin recopilación de datos personales ni seguimiento.', 'hero'),

('es', 'featured_vendors.title', 'Vendedores Destacados', 'vendors'),
('es', 'featured_vendors.subtitle', 'Descubre vendedores verificados de alta calificación en nuestro mercado seguro', 'vendors'),
('es', 'featured_vendors.view_all', 'Ver Todos los Vendedores', 'vendors'),

('es', 'footer.description', 'El mercado anónimo más seguro del mundo. Comercia con confianza usando Bitcoin, vendedores verificados y sistemas de seguridad impulsados por IA.', 'footer'),
('es', 'footer.encrypted', 'Cifrado de Extremo a Extremo', 'footer'),
('es', 'footer.ai_powered', 'Impulsado por IA', 'footer'),
('es', 'footer.menu.marketplace', 'Mercado', 'footer'),
('es', 'footer.menu.browse_products', 'Explorar Productos', 'footer'),
('es', 'footer.menu.verified_vendors', 'Vendedores Verificados', 'footer'),
('es', 'footer.menu.how_to_order', 'Cómo Ordenar', 'footer'),
('es', 'footer.menu.selling_guide', 'Guía de Venta', 'footer'),
('es', 'footer.menu.escrow_security', 'Seguridad de Depósito', 'footer'),
('es', 'footer.menu.categories', 'Categorías', 'footer'),
('es', 'footer.menu.support', 'Soporte', 'footer'),
('es', 'footer.menu.faq', 'Preguntas Frecuentes', 'footer'),
('es', 'footer.menu.about_us', 'Acerca de Nosotros', 'footer'),
('es', 'footer.menu.contact', 'Contacto', 'footer'),
('es', 'footer.menu.forbidden', 'Seguridad y Términos', 'footer'),
('es', 'footer.menu.pgp_tools', 'Herramientas PGP', 'footer'),
('es', 'footer.menu.help_center', 'Centro de Ayuda', 'footer'),
('es', 'footer.copyright', '© 2024 OpesMarket. Seguro, Anónimo, Descentralizado.', 'footer'),
('es', 'footer.status.secure', 'Seguro y En Línea', 'footer'),
('es', 'footer.status.online', 'Disponible 24/7', 'footer'),

('es', 'about.title', 'Acerca de OpesMarket', 'about'),
('es', 'about.subtitle', 'El mercado anónimo premier impulsado por IA para transacciones seguras de Bitcoin', 'about'),
('es', 'about.mission.title', 'Nuestra Misión', 'about'),
('es', 'about.mission.content', 'OpesMarket está revolucionando el comercio en línea proporcionando el mercado más seguro, privado e inteligente del mundo. Creemos en la verdadera libertad digital donde la privacidad es primordial, las transacciones son transparentes y la confianza se construye a través de tecnología de IA de vanguardia.', 'about'),
('es', 'about.features.bitcoin.title', 'Solo Bitcoin', 'about'),
('es', 'about.features.bitcoin.desc', 'Pagos completamente descentralizados usando solo Bitcoin, asegurando verdadera soberanía financiera y privacidad.', 'about'),
('es', 'about.features.security.title', 'Seguridad de Grado Militar', 'about'),
('es', 'about.features.security.desc', 'Cifrado avanzado, depósito multi-firma y detección de fraude impulsada por IA protegen cada transacción.', 'about'),
('es', 'about.features.privacy.title', 'Privacidad Completa', 'about'),
('es', 'about.features.privacy.desc', 'Cero recopilación de datos personales con navegación anónima y comunicaciones cifradas PGP.', 'about'),
('es', 'about.features.community.title', 'Comunidad Confiable', 'about'),
('es', 'about.features.community.desc', 'Vendedores verificados con puntuaciones de confianza basadas en reputación y comentarios transparentes de la comunidad.', 'about'),
('es', 'about.features.ai.title', 'Inteligencia Impulsada por IA', 'about'),
('es', 'about.features.ai.desc', 'Recomendaciones inteligentes, monitoreo automatizado de seguridad y resolución inteligente de disputas.', 'about'),
('es', 'about.features.global.title', 'Accesibilidad Global', 'about'),
('es', 'about.features.global.desc', 'Disponible en todo el mundo con soporte multilingüe y transacciones transfronterizas sin problemas.', 'about'),

('es', 'contact.title', 'Contactar OpesMarket', 'contact'),
('es', 'contact.subtitle', 'Ponte en contacto con nuestro equipo para soporte, preguntas o consultas de asociación. Todas las comunicaciones están cifradas y son seguras.', 'contact'),
('es', 'contact.form.title', 'Formulario de Contacto Seguro', 'contact'),
('es', 'contact.form.subject', 'Asunto', 'contact'),
('es', 'contact.form.subject_placeholder', 'Breve descripción de tu consulta', 'contact'),
('es', 'contact.form.urgency', 'Nivel de Prioridad', 'contact'),
('es', 'contact.form.urgency.low', 'Bajo - Consulta general', 'contact'),
('es', 'contact.form.urgency.normal', 'Normal - Soporte estándar', 'contact'),
('es', 'contact.form.urgency.high', 'Alto - Problema técnico', 'contact'),
('es', 'contact.form.urgency.urgent', 'Urgente - Preocupación de seguridad', 'contact'),
('es', 'contact.form.message', 'Mensaje', 'contact'),
('es', 'contact.form.message_placeholder', 'Por favor proporciona información detallada sobre tu consulta o problema...', 'contact'),
('es', 'contact.form.send', 'Enviar Mensaje Seguro', 'contact'),
('es', 'contact.success.title', 'Mensaje Enviado', 'contact'),
('es', 'contact.success.description', 'Tu mensaje seguro ha sido recibido. Responderemos dentro de 24 horas.', 'contact'),
('es', 'contact.response.title', 'Tiempos de Respuesta', 'contact'),
('es', 'contact.response.general', 'Consultas Generales', 'contact'),
('es', 'contact.response.technical', 'Soporte Técnico', 'contact'),
('es', 'contact.response.security', 'Problemas de Seguridad', 'contact'),
('es', 'contact.response.urgent', 'Asuntos Urgentes', 'contact'),
('es', 'contact.topics.title', 'Temas Comunes', 'contact'),
('es', 'contact.security.title', 'Aviso de Seguridad', 'contact'),
('es', 'contact.security.description', 'Todas las comunicaciones están cifradas de extremo a extremo. Nunca pedimos contraseñas, claves privadas o información sensible a través de canales de soporte.', 'contact'),

('es', 'shop.title', 'Explorar Productos', 'shop'),
('es', 'shop.search.placeholder', 'Descubre productos verificados de vendedores confiables', 'shop'),
('es', 'shop.filters.category', 'Categoría', 'shop'),
('es', 'shop.filters.all_categories', 'Todas las Categorías', 'shop'),
('es', 'shop.filters.price_range', 'Rango de Precio (BTC)', 'shop'),
('es', 'shop.filters.sort_by', 'Ordenar Por', 'shop'),
('es', 'shop.filters.newest', 'Más Recientes', 'shop'),
('es', 'shop.filters.price_low', 'Precio: Bajo a Alto', 'shop'),
('es', 'shop.filters.price_high', 'Precio: Alto a Bajo', 'shop'),
('es', 'shop.filters.rating', 'Más Popular', 'shop'),
('es', 'shop.top_vendors.title', 'Mejores Vendedores', 'shop'),

('es', 'ui.search', 'Buscar', 'ui'),
('es', 'vendor.verified', 'Vendedores Verificados', 'vendor'),

-- French translations
('fr', 'nav.search', 'Rechercher produits, vendeurs...', 'navigation'),
('fr', 'nav.shop', 'Boutique', 'navigation'),
('fr', 'nav.forum', 'Forum', 'navigation'),
('fr', 'nav.wishlist', 'Liste de Souhaits', 'navigation'),
('fr', 'nav.affiliate', 'Affilié', 'navigation'),
('fr', 'nav.orders', 'Mes Commandes', 'navigation'),
('fr', 'nav.messages', 'Messages', 'navigation'),
('fr', 'nav.profile', 'Profil', 'navigation'),
('fr', 'nav.become_vendor', 'Devenir Vendeur', 'navigation'),
('fr', 'nav.logout', 'Se Déconnecter', 'navigation'),
('fr', 'nav.login', 'Se Connecter', 'navigation'),

('fr', 'hero.title.ai_powered', 'Alimenté par l''IA', 'hero'),
('fr', 'hero.title.anonymous_marketplace', 'Marché Anonyme', 'hero'),
('fr', 'hero.subtitle', 'Commercez en sécurité avec des transactions Bitcoin uniquement, des vendeurs vérifiés et un scoring de confiance piloté par l''IA.', 'hero'),
('fr', 'hero.cta.start_shopping', 'Commencer les Achats', 'hero'),
('fr', 'hero.cta.become_vendor', 'Devenir Vendeur', 'hero'),
('fr', 'hero.feature.bitcoin_only', 'Bitcoin Uniquement', 'hero'),
('fr', 'hero.feature.bitcoin_desc', 'Paiements entièrement décentralisés utilisant uniquement Bitcoin pour une vraie liberté financière.', 'hero'),
('fr', 'hero.feature.verified_vendors', 'Vendeurs Vérifiés', 'hero'),
('fr', 'hero.feature.verified_desc', 'Vendeurs vérifiés par IA avec des systèmes transparents de réputation et scoring de confiance.', 'hero'),
('fr', 'hero.feature.ai_powered', 'Alimenté par l''IA', 'hero'),
('fr', 'hero.feature.ai_desc', 'Recommandations intelligentes et sécurité automatisée pour la meilleure expérience.', 'hero'),
('fr', 'hero.feature.anonymous', 'Anonyme', 'hero'),
('fr', 'hero.feature.anonymous_desc', 'Confidentialité complète sans collecte de données personnelles ni suivi.', 'hero'),

('fr', 'featured_vendors.title', 'Vendeurs en Vedette', 'vendors'),
('fr', 'featured_vendors.subtitle', 'Découvrez des vendeurs vérifiés et bien notés dans notre marché sécurisé', 'vendors'),
('fr', 'featured_vendors.view_all', 'Voir Tous les Vendeurs', 'vendors'),

('fr', 'footer.description', 'Le marché anonyme le plus sécurisé au monde. Commercez en confiance avec Bitcoin, des vendeurs vérifiés et des systèmes de sécurité alimentés par l''IA.', 'footer'),
('fr', 'footer.encrypted', 'Chiffré de Bout en Bout', 'footer'),
('fr', 'footer.ai_powered', 'Alimenté par l''IA', 'footer'),
('fr', 'footer.menu.marketplace', 'Marché', 'footer'),
('fr', 'footer.menu.browse_products', 'Parcourir les Produits', 'footer'),
('fr', 'footer.menu.verified_vendors', 'Vendeurs Vérifiés', 'footer'),
('fr', 'footer.menu.how_to_order', 'Comment Commander', 'footer'),
('fr', 'footer.menu.selling_guide', 'Guide de Vente', 'footer'),
('fr', 'footer.menu.escrow_security', 'Sécurité Escrow', 'footer'),
('fr', 'footer.menu.categories', 'Catégories', 'footer'),
('fr', 'footer.menu.support', 'Support', 'footer'),
('fr', 'footer.menu.faq', 'FAQ', 'footer'),
('fr', 'footer.menu.about_us', 'À Propos', 'footer'),
('fr', 'footer.menu.contact', 'Contact', 'footer'),
('fr', 'footer.menu.forbidden', 'Sécurité et Conditions', 'footer'),
('fr', 'footer.menu.pgp_tools', 'Outils PGP', 'footer'),
('fr', 'footer.menu.help_center', 'Centre d''Aide', 'footer'),
('fr', 'footer.copyright', '© 2024 OpesMarket. Sécurisé, Anonyme, Décentralisé.', 'footer'),
('fr', 'footer.status.secure', 'Sécurisé et En Ligne', 'footer'),
('fr', 'footer.status.online', 'Disponible 24/7', 'footer'),

('fr', 'about.title', 'À Propos d''OpesMarket', 'about'),
('fr', 'about.subtitle', 'Le marché anonyme premier alimenté par l''IA pour des transactions Bitcoin sécurisées', 'about'),
('fr', 'about.mission.title', 'Notre Mission', 'about'),
('fr', 'about.mission.content', 'OpesMarket révolutionne le commerce en ligne en fournissant le marché le plus sécurisé, privé et intelligent au monde. Nous croyons en la vraie liberté numérique où la confidentialité est primordiale.', 'about'),
('fr', 'about.features.bitcoin.title', 'Bitcoin Uniquement', 'about'),
('fr', 'about.features.bitcoin.desc', 'Paiements entièrement décentralisés utilisant uniquement Bitcoin, garantissant une vraie souveraineté financière et confidentialité.', 'about'),
('fr', 'about.features.security.title', 'Sécurité de Grade Militaire', 'about'),
('fr', 'about.features.security.desc', 'Chiffrement avancé, escrow multi-signature et détection de fraude alimentée par l''IA protègent chaque transaction.', 'about'),
('fr', 'about.features.privacy.title', 'Confidentialité Complète', 'about'),
('fr', 'about.features.privacy.desc', 'Zéro collecte de données personnelles avec navigation anonyme et communications chiffrées PGP.', 'about'),
('fr', 'about.features.community.title', 'Communauté de Confiance', 'about'),
('fr', 'about.features.community.desc', 'Vendeurs vérifiés avec des scores de confiance basés sur la réputation et des commentaires transparents de la communauté.', 'about'),
('fr', 'about.features.ai.title', 'Intelligence Alimentée par l''IA', 'about'),
('fr', 'about.features.ai.desc', 'Recommandations intelligentes, surveillance automatisée de sécurité et résolution intelligente de litiges.', 'about'),
('fr', 'about.features.global.title', 'Accessibilité Globale', 'about'),
('fr', 'about.features.global.desc', 'Disponible dans le monde entier avec support multilingue et transactions transfrontalières transparentes.', 'about'),

('fr', 'contact.title', 'Contacter OpesMarket', 'contact'),
('fr', 'contact.subtitle', 'Contactez notre équipe pour le support, les questions ou les demandes de partenariat. Toutes les communications sont chiffrées et sécurisées.', 'contact'),
('fr', 'contact.form.title', 'Formulaire de Contact Sécurisé', 'contact'),
('fr', 'contact.form.subject', 'Sujet', 'contact'),
('fr', 'contact.form.subject_placeholder', 'Brève description de votre demande', 'contact'),
('fr', 'contact.form.urgency', 'Niveau de Priorité', 'contact'),
('fr', 'contact.form.urgency.low', 'Bas - Demande générale', 'contact'),
('fr', 'contact.form.urgency.normal', 'Normal - Support standard', 'contact'),
('fr', 'contact.form.urgency.high', 'Élevé - Problème technique', 'contact'),
('fr', 'contact.form.urgency.urgent', 'Urgent - Préoccupation de sécurité', 'contact'),
('fr', 'contact.form.message', 'Message', 'contact'),
('fr', 'contact.form.message_placeholder', 'Veuillez fournir des informations détaillées sur votre demande ou problème...', 'contact'),
('fr', 'contact.form.send', 'Envoyer Message Sécurisé', 'contact'),
('fr', 'contact.success.title', 'Message Envoyé', 'contact'),
('fr', 'contact.success.description', 'Votre message sécurisé a été reçu. Nous répondrons dans les 24 heures.', 'contact'),
('fr', 'contact.response.title', 'Temps de Réponse', 'contact'),
('fr', 'contact.response.general', 'Demandes Générales', 'contact'),
('fr', 'contact.response.technical', 'Support Technique', 'contact'),
('fr', 'contact.response.security', 'Problèmes de Sécurité', 'contact'),
('fr', 'contact.response.urgent', 'Affaires Urgentes', 'contact'),
('fr', 'contact.topics.title', 'Sujets Communs', 'contact'),
('fr', 'contact.security.title', 'Avis de Sécurité', 'contact'),
('fr', 'contact.security.description', 'Toutes les communications sont chiffrées de bout en bout. Nous ne demandons jamais de mots de passe, clés privées ou informations sensibles via les canaux de support.', 'contact'),

('fr', 'shop.title', 'Parcourir les Produits', 'shop'),
('fr', 'shop.search.placeholder', 'Découvrez des produits vérifiés de vendeurs de confiance', 'shop'),
('fr', 'shop.filters.category', 'Catégorie', 'shop'),
('fr', 'shop.filters.all_categories', 'Toutes les Catégories', 'shop'),
('fr', 'shop.filters.price_range', 'Gamme de Prix (BTC)', 'shop'),
('fr', 'shop.filters.sort_by', 'Trier Par', 'shop'),
('fr', 'shop.filters.newest', 'Plus Récents', 'shop'),
('fr', 'shop.filters.price_low', 'Prix: Bas à Élevé', 'shop'),
('fr', 'shop.filters.price_high', 'Prix: Élevé à Bas', 'shop'),
('fr', 'shop.filters.rating', 'Plus Populaire', 'shop'),
('fr', 'shop.top_vendors.title', 'Meilleurs Vendeurs', 'shop'),

('fr', 'ui.search', 'Rechercher', 'ui'),
('fr', 'vendor.verified', 'Vendeurs Vérifiés', 'vendor'),

-- German translations
('de', 'nav.search', 'Produkte, Verkäufer suchen...', 'navigation'),
('de', 'nav.shop', 'Shop', 'navigation'),
('de', 'nav.forum', 'Forum', 'navigation'),
('de', 'nav.wishlist', 'Wunschliste', 'navigation'),
('de', 'nav.affiliate', 'Partner', 'navigation'),
('de', 'nav.orders', 'Meine Bestellungen', 'navigation'),
('de', 'nav.messages', 'Nachrichten', 'navigation'),
('de', 'nav.profile', 'Profil', 'navigation'),
('de', 'nav.become_vendor', 'Verkäufer Werden', 'navigation'),
('de', 'nav.logout', 'Abmelden', 'navigation'),
('de', 'nav.login', 'Anmelden', 'navigation'),

('de', 'hero.title.ai_powered', 'KI-Betrieben', 'hero'),
('de', 'hero.title.anonymous_marketplace', 'Anonymer Marktplatz', 'hero'),
('de', 'hero.subtitle', 'Handeln Sie sicher mit reinen Bitcoin-Transaktionen, verifizierten Verkäufern und KI-gesteuerter Vertrauensbewertung.', 'hero'),
('de', 'hero.cta.start_shopping', 'Einkaufen Beginnen', 'hero'),
('de', 'hero.cta.become_vendor', 'Verkäufer Werden', 'hero'),
('de', 'hero.feature.bitcoin_only', 'Nur Bitcoin', 'hero'),
('de', 'hero.feature.bitcoin_desc', 'Vollständig dezentralisierte Zahlungen nur mit Bitcoin für wahre finanzielle Freiheit.', 'hero'),
('de', 'hero.feature.verified_vendors', 'Verifizierte Verkäufer', 'hero'),
('de', 'hero.feature.verified_desc', 'KI-verifizierte Verkäufer mit transparenten Reputations- und Vertrauensbewertungssystemen.', 'hero'),
('de', 'hero.feature.ai_powered', 'KI-Betrieben', 'hero'),
('de', 'hero.feature.ai_desc', 'Intelligente Empfehlungen und automatisierte Sicherheit für die beste Erfahrung.', 'hero'),
('de', 'hero.feature.anonymous', 'Anonym', 'hero'),
('de', 'hero.feature.anonymous_desc', 'Vollständige Privatsphäre ohne Sammlung persönlicher Daten oder Verfolgung.', 'hero'),

('de', 'featured_vendors.title', 'Ausgewählte Verkäufer', 'vendors'),
('de', 'featured_vendors.subtitle', 'Entdecken Sie hochbewertete, verifizierte Verkäufer in unserem sicheren Marktplatz', 'vendors'),
('de', 'featured_vendors.view_all', 'Alle Verkäufer Anzeigen', 'vendors'),

('de', 'footer.description', 'Der sicherste anonyme Marktplatz der Welt. Handeln Sie vertrauensvoll mit Bitcoin, verifizierten Verkäufern und KI-betriebenen Sicherheitssystemen.', 'footer'),
('de', 'footer.encrypted', 'Ende-zu-Ende Verschlüsselt', 'footer'),
('de', 'footer.ai_powered', 'KI-Betrieben', 'footer'),
('de', 'footer.menu.marketplace', 'Marktplatz', 'footer'),
('de', 'footer.menu.browse_products', 'Produkte Durchsuchen', 'footer'),
('de', 'footer.menu.verified_vendors', 'Verifizierte Verkäufer', 'footer'),
('de', 'footer.menu.how_to_order', 'Wie Bestellen', 'footer'),
('de', 'footer.menu.selling_guide', 'Verkaufsleitfaden', 'footer'),
('de', 'footer.menu.escrow_security', 'Treuhand-Sicherheit', 'footer'),
('de', 'footer.menu.categories', 'Kategorien', 'footer'),
('de', 'footer.menu.support', 'Support', 'footer'),
('de', 'footer.menu.faq', 'FAQ', 'footer'),
('de', 'footer.menu.about_us', 'Über Uns', 'footer'),
('de', 'footer.menu.contact', 'Kontakt', 'footer'),
('de', 'footer.menu.forbidden', 'Sicherheit und Bedingungen', 'footer'),
('de', 'footer.menu.pgp_tools', 'PGP-Tools', 'footer'),
('de', 'footer.menu.help_center', 'Hilfezentrum', 'footer'),
('de', 'footer.copyright', '© 2024 OpesMarket. Sicher, Anonym, Dezentralisiert.', 'footer'),
('de', 'footer.status.secure', 'Sicher und Online', 'footer'),
('de', 'footer.status.online', '24/7 Verfügbar', 'footer'),

('de', 'about.title', 'Über OpesMarket', 'about'),
('de', 'about.subtitle', 'Der führende KI-betriebene anonyme Marktplatz für sichere Bitcoin-Transaktionen', 'about'),
('de', 'about.mission.title', 'Unsere Mission', 'about'),
('de', 'about.mission.content', 'OpesMarket revolutioniert den Online-Handel durch die Bereitstellung des sichersten, privatesten und intelligentesten Marktplatzes der Welt. Wir glauben an wahre digitale Freiheit, wo Privatsphäre oberste Priorität hat.', 'about'),
('de', 'about.features.bitcoin.title', 'Nur Bitcoin', 'about'),
('de', 'about.features.bitcoin.desc', 'Vollständig dezentralisierte Zahlungen nur mit Bitcoin, die wahre finanzielle Souveränität und Privatsphäre gewährleisten.', 'about'),
('de', 'about.features.security.title', 'Militärische Sicherheit', 'about'),
('de', 'about.features.security.desc', 'Erweiterte Verschlüsselung, Multi-Signatur-Treuhand und KI-betriebene Betrugserkennung schützen jede Transaktion.', 'about'),
('de', 'about.features.privacy.title', 'Vollständige Privatsphäre', 'about'),
('de', 'about.features.privacy.desc', 'Null persönliche Datensammlung mit anonymem Browsen und PGP-verschlüsselter Kommunikation.', 'about'),
('de', 'about.features.community.title', 'Vertrauensgemeinschaft', 'about'),
('de', 'about.features.community.desc', 'Verifizierte Verkäufer mit reputationsbasierten Vertrauenswerten und transparentem Community-Feedback.', 'about'),
('de', 'about.features.ai.title', 'KI-Betriebene Intelligenz', 'about'),
('de', 'about.features.ai.desc', 'Intelligente Empfehlungen, automatisierte Sicherheitsüberwachung und intelligente Streitbeilegung.', 'about'),
('de', 'about.features.global.title', 'Globale Zugänglichkeit', 'about'),
('de', 'about.features.global.desc', 'Weltweit verfügbar mit mehrsprachiger Unterstützung und nahtlosen grenzüberschreitenden Transaktionen.', 'about'),

('de', 'contact.title', 'OpesMarket Kontaktieren', 'contact'),
('de', 'contact.subtitle', 'Kontaktieren Sie unser Team für Support, Fragen oder Partnerschaftsanfragen. Alle Kommunikationen sind verschlüsselt und sicher.', 'contact'),
('de', 'contact.form.title', 'Sicheres Kontaktformular', 'contact'),
('de', 'contact.form.subject', 'Betreff', 'contact'),
('de', 'contact.form.subject_placeholder', 'Kurze Beschreibung Ihrer Anfrage', 'contact'),
('de', 'contact.form.urgency', 'Prioritätsstufe', 'contact'),
('de', 'contact.form.urgency.low', 'Niedrig - Allgemeine Anfrage', 'contact'),
('de', 'contact.form.urgency.normal', 'Normal - Standard-Support', 'contact'),
('de', 'contact.form.urgency.high', 'Hoch - Technisches Problem', 'contact'),
('de', 'contact.form.urgency.urgent', 'Dringend - Sicherheitsbedenken', 'contact'),
('de', 'contact.form.message', 'Nachricht', 'contact'),
('de', 'contact.form.message_placeholder', 'Bitte geben Sie detaillierte Informationen zu Ihrer Anfrage oder Ihrem Problem an...', 'contact'),
('de', 'contact.form.send', 'Sichere Nachricht Senden', 'contact'),
('de', 'contact.success.title', 'Nachricht Gesendet', 'contact'),
('de', 'contact.success.description', 'Ihre sichere Nachricht wurde empfangen. Wir werden innerhalb von 24 Stunden antworten.', 'contact'),
('de', 'contact.response.title', 'Antwortzeiten', 'contact'),
('de', 'contact.response.general', 'Allgemeine Anfragen', 'contact'),
('de', 'contact.response.technical', 'Technischer Support', 'contact'),
('de', 'contact.response.security', 'Sicherheitsprobleme', 'contact'),
('de', 'contact.response.urgent', 'Dringende Angelegenheiten', 'contact'),
('de', 'contact.topics.title', 'Häufige Themen', 'contact'),
('de', 'contact.security.title', 'Sicherheitshinweis', 'contact'),
('de', 'contact.security.description', 'Alle Kommunikationen sind Ende-zu-Ende verschlüsselt. Wir fragen niemals nach Passwörtern, privaten Schlüsseln oder sensiblen Informationen über Support-Kanäle.', 'contact'),

('de', 'shop.title', 'Produkte Durchsuchen', 'shop'),
('de', 'shop.search.placeholder', 'Entdecken Sie verifizierte Produkte von vertrauenswürdigen Verkäufern', 'shop'),
('de', 'shop.filters.category', 'Kategorie', 'shop'),
('de', 'shop.filters.all_categories', 'Alle Kategorien', 'shop'),
('de', 'shop.filters.price_range', 'Preisbereich (BTC)', 'shop'),
('de', 'shop.filters.sort_by', 'Sortieren Nach', 'shop'),
('de', 'shop.filters.newest', 'Neueste Zuerst', 'shop'),
('de', 'shop.filters.price_low', 'Preis: Niedrig zu Hoch', 'shop'),
('de', 'shop.filters.price_high', 'Preis: Hoch zu Niedrig', 'shop'),
('de', 'shop.filters.rating', 'Beliebteste', 'shop'),
('de', 'shop.top_vendors.title', 'Top Verkäufer', 'shop'),

('de', 'ui.search', 'Suchen', 'ui'),
('de', 'vendor.verified', 'Verifizierte Verkäufer', 'vendor')

ON CONFLICT (language_code, translation_key, context) DO UPDATE SET 
  translation_value = EXCLUDED.translation_value;