-- Add comprehensive translations for all pages, footer menu, and missing components
INSERT INTO public.translations (language_code, translation_key, translation_value, context) VALUES

-- Footer menu translations (English)
('en', 'footer.menu.marketplace', 'Marketplace', 'footer'),
('en', 'footer.menu.browse_products', 'Browse Products', 'footer'),
('en', 'footer.menu.verified_vendors', 'Verified Vendors', 'footer'),
('en', 'footer.menu.how_to_order', 'How to Order', 'footer'),
('en', 'footer.menu.selling_guide', 'Selling Guide', 'footer'),
('en', 'footer.menu.escrow_security', 'Escrow Security', 'footer'),
('en', 'footer.menu.categories', 'Categories', 'footer'),
('en', 'footer.menu.support', 'Support', 'footer'),
('en', 'footer.menu.faq', 'FAQ', 'footer'),
('en', 'footer.menu.about_us', 'About Us', 'footer'),
('en', 'footer.menu.contact', 'Contact', 'footer'),
('en', 'footer.menu.forbidden', 'Forbidden in Opes Market', 'footer'),
('en', 'footer.menu.pgp_tools', 'PGP Tools', 'footer'),
('en', 'footer.menu.help_center', 'Help Center', 'footer'),
('en', 'footer.copyright', '© 2025 OpesMarket. All rights reserved. Bitcoin-only anonymous marketplace.', 'footer'),
('en', 'footer.status.secure', 'Secure • Anonymous • AI-Powered', 'footer'),
('en', 'footer.status.online', 'Online', 'footer'),

-- About page translations (English)
('en', 'about.title', 'About OpesMarket', 'about'),
('en', 'about.subtitle', 'The world\'s most secure anonymous marketplace, powered by Bitcoin and AI technology.', 'about'),
('en', 'about.mission.title', 'Our Mission', 'about'),
('en', 'about.mission.content', 'OpesMarket is dedicated to creating a secure, anonymous, and trustworthy marketplace where privacy is paramount. We leverage cutting-edge Bitcoin technology and AI-powered security systems to ensure safe transactions while maintaining complete user anonymity.', 'about'),
('en', 'about.features.bitcoin.title', 'Bitcoin Only', 'about'),
('en', 'about.features.bitcoin.desc', 'All transactions are conducted exclusively in Bitcoin, ensuring complete financial privacy and decentralization.', 'about'),
('en', 'about.features.security.title', 'Advanced Security', 'about'),
('en', 'about.features.security.desc', 'Multi-layered security protocols protect all users and transactions from potential threats.', 'about'),
('en', 'about.features.community.title', 'Trusted Community', 'about'),
('en', 'about.features.community.desc', 'Our verified vendor system ensures quality and reliability in every transaction.', 'about'),
('en', 'about.features.ai.title', 'AI-Powered', 'about'),
('en', 'about.features.ai.desc', 'Intelligent algorithms provide fraud detection, trust scoring, and enhanced user experience.', 'about'),
('en', 'about.features.global.title', 'Global Access', 'about'),
('en', 'about.features.global.desc', 'Available worldwide with support for multiple languages and Tor network compatibility.', 'about'),
('en', 'about.features.privacy.title', 'Complete Privacy', 'about'),
('en', 'about.features.privacy.desc', 'End-to-end encryption and anonymous browsing ensure your identity remains protected.', 'about'),

-- Shop page translations (English)
('en', 'shop.title', 'Marketplace', 'shop'),
('en', 'shop.search.placeholder', 'Search products...', 'shop'),
('en', 'shop.filters.category', 'Category', 'shop'),
('en', 'shop.filters.all_categories', 'All Categories', 'shop'),
('en', 'shop.filters.price_range', 'Price Range', 'shop'),
('en', 'shop.filters.all_prices', 'All Prices', 'shop'),
('en', 'shop.filters.sort_by', 'Sort By', 'shop'),
('en', 'shop.filters.newest', 'Newest', 'shop'),
('en', 'shop.filters.price_low', 'Price: Low to High', 'shop'),
('en', 'shop.filters.price_high', 'Price: High to Low', 'shop'),
('en', 'shop.filters.rating', 'Highest Rated', 'shop'),
('en', 'shop.top_vendors.title', 'Top Vendors', 'shop'),
('en', 'shop.trending.title', 'Trending Categories', 'shop'),

-- Common UI translations (English)
('en', 'ui.search', 'Search', 'ui'),
('en', 'ui.filter', 'Filter', 'ui'),
('en', 'ui.clear_filters', 'Clear Filters', 'ui'),
('en', 'ui.no_results', 'No results found', 'ui'),
('en', 'ui.load_more', 'Load More', 'ui'),
('en', 'ui.view_all', 'View All', 'ui'),

-- SPANISH TRANSLATIONS --
-- Footer menu (Spanish)
('es', 'footer.menu.marketplace', 'Mercado', 'footer'),
('es', 'footer.menu.browse_products', 'Explorar Productos', 'footer'),
('es', 'footer.menu.verified_vendors', 'Vendedores Verificados', 'footer'),
('es', 'footer.menu.how_to_order', 'Cómo Ordenar', 'footer'),
('es', 'footer.menu.selling_guide', 'Guía de Ventas', 'footer'),
('es', 'footer.menu.escrow_security', 'Seguridad de Depósito', 'footer'),
('es', 'footer.menu.categories', 'Categorías', 'footer'),
('es', 'footer.menu.support', 'Soporte', 'footer'),
('es', 'footer.menu.faq', 'Preguntas Frecuentes', 'footer'),
('es', 'footer.menu.about_us', 'Acerca de Nosotros', 'footer'),
('es', 'footer.menu.contact', 'Contacto', 'footer'),
('es', 'footer.menu.forbidden', 'Prohibido en Opes Market', 'footer'),
('es', 'footer.menu.pgp_tools', 'Herramientas PGP', 'footer'),
('es', 'footer.menu.help_center', 'Centro de Ayuda', 'footer'),
('es', 'footer.copyright', '© 2025 OpesMarket. Todos los derechos reservados. Mercado anónimo solo con Bitcoin.', 'footer'),
('es', 'footer.status.secure', 'Seguro • Anónimo • Impulsado por IA', 'footer'),
('es', 'footer.status.online', 'En línea', 'footer'),

-- About page (Spanish)
('es', 'about.title', 'Acerca de OpesMarket', 'about'),
('es', 'about.subtitle', 'El mercado anónimo más seguro del mundo, impulsado por Bitcoin y tecnología de IA.', 'about'),
('es', 'about.mission.title', 'Nuestra Misión', 'about'),
('es', 'about.mission.content', 'OpesMarket está dedicado a crear un mercado seguro, anónimo y confiable donde la privacidad es primordial. Aprovechamos la tecnología de vanguardia de Bitcoin y sistemas de seguridad impulsados por IA para garantizar transacciones seguras mientras mantenemos el completo anonimato del usuario.', 'about'),
('es', 'about.features.bitcoin.title', 'Solo Bitcoin', 'about'),
('es', 'about.features.bitcoin.desc', 'Todas las transacciones se realizan exclusivamente en Bitcoin, garantizando completa privacidad financiera y descentralización.', 'about'),
('es', 'about.features.security.title', 'Seguridad Avanzada', 'about'),
('es', 'about.features.security.desc', 'Protocolos de seguridad multicapa protegen a todos los usuarios y transacciones de amenazas potenciales.', 'about'),
('es', 'about.features.community.title', 'Comunidad Confiable', 'about'),
('es', 'about.features.community.desc', 'Nuestro sistema de vendedores verificados garantiza calidad y confiabilidad en cada transacción.', 'about'),
('es', 'about.features.ai.title', 'Impulsado por IA', 'about'),
('es', 'about.features.ai.desc', 'Algoritmos inteligentes proporcionan detección de fraudes, puntuación de confianza y experiencia de usuario mejorada.', 'about'),
('es', 'about.features.global.title', 'Acceso Global', 'about'),
('es', 'about.features.global.desc', 'Disponible en todo el mundo con soporte para múltiples idiomas y compatibilidad con la red Tor.', 'about'),
('es', 'about.features.privacy.title', 'Privacidad Completa', 'about'),
('es', 'about.features.privacy.desc', 'Cifrado de extremo a extremo y navegación anónima aseguran que tu identidad permanezca protegida.', 'about'),

-- Shop page (Spanish)
('es', 'shop.title', 'Mercado', 'shop'),
('es', 'shop.search.placeholder', 'Buscar productos...', 'shop'),
('es', 'shop.filters.category', 'Categoría', 'shop'),
('es', 'shop.filters.all_categories', 'Todas las Categorías', 'shop'),
('es', 'shop.filters.price_range', 'Rango de Precio', 'shop'),
('es', 'shop.filters.all_prices', 'Todos los Precios', 'shop'),
('es', 'shop.filters.sort_by', 'Ordenar Por', 'shop'),
('es', 'shop.filters.newest', 'Más Nuevo', 'shop'),
('es', 'shop.filters.price_low', 'Precio: Menor a Mayor', 'shop'),
('es', 'shop.filters.price_high', 'Precio: Mayor a Menor', 'shop'),
('es', 'shop.filters.rating', 'Mejor Calificado', 'shop'),
('es', 'shop.top_vendors.title', 'Mejores Vendedores', 'shop'),
('es', 'shop.trending.title', 'Categorías Populares', 'shop'),

-- Common UI (Spanish)
('es', 'ui.search', 'Buscar', 'ui'),
('es', 'ui.filter', 'Filtrar', 'ui'),
('es', 'ui.clear_filters', 'Limpiar Filtros', 'ui'),
('es', 'ui.no_results', 'No se encontraron resultados', 'ui'),
('es', 'ui.load_more', 'Cargar Más', 'ui'),
('es', 'ui.view_all', 'Ver Todo', 'ui'),

-- FRENCH TRANSLATIONS --
-- Footer menu (French)
('fr', 'footer.menu.marketplace', 'Marché', 'footer'),
('fr', 'footer.menu.browse_products', 'Parcourir les Produits', 'footer'),
('fr', 'footer.menu.verified_vendors', 'Vendeurs Vérifiés', 'footer'),
('fr', 'footer.menu.how_to_order', 'Comment Commander', 'footer'),
('fr', 'footer.menu.selling_guide', 'Guide de Vente', 'footer'),
('fr', 'footer.menu.escrow_security', 'Sécurité Escrow', 'footer'),
('fr', 'footer.menu.categories', 'Catégories', 'footer'),
('fr', 'footer.menu.support', 'Support', 'footer'),
('fr', 'footer.menu.faq', 'FAQ', 'footer'),
('fr', 'footer.menu.about_us', 'À Propos', 'footer'),
('fr', 'footer.menu.contact', 'Contact', 'footer'),
('fr', 'footer.menu.forbidden', 'Interdit sur Opes Market', 'footer'),
('fr', 'footer.menu.pgp_tools', 'Outils PGP', 'footer'),
('fr', 'footer.menu.help_center', 'Centre d\'Aide', 'footer'),
('fr', 'footer.copyright', '© 2025 OpesMarket. Tous droits réservés. Marché anonyme Bitcoin uniquement.', 'footer'),
('fr', 'footer.status.secure', 'Sécurisé • Anonyme • Alimenté par IA', 'footer'),
('fr', 'footer.status.online', 'En ligne', 'footer'),

-- About page (French)
('fr', 'about.title', 'À Propos d\'OpesMarket', 'about'),
('fr', 'about.subtitle', 'Le marché anonyme le plus sécurisé au monde, alimenté par Bitcoin et la technologie IA.', 'about'),
('fr', 'about.mission.title', 'Notre Mission', 'about'),
('fr', 'about.mission.content', 'OpesMarket se consacre à créer un marché sécurisé, anonyme et fiable où la confidentialité est primordiale. Nous exploitons la technologie Bitcoin de pointe et les systèmes de sécurité alimentés par IA pour assurer des transactions sûres tout en maintenant un anonymat complet des utilisateurs.', 'about'),
('fr', 'about.features.bitcoin.title', 'Bitcoin Uniquement', 'about'),
('fr', 'about.features.bitcoin.desc', 'Toutes les transactions sont effectuées exclusivement en Bitcoin, garantissant une confidentialité financière complète et la décentralisation.', 'about'),
('fr', 'about.features.security.title', 'Sécurité Avancée', 'about'),
('fr', 'about.features.security.desc', 'Les protocoles de sécurité multicouches protègent tous les utilisateurs et transactions contre les menaces potentielles.', 'about'),
('fr', 'about.features.community.title', 'Communauté de Confiance', 'about'),
('fr', 'about.features.community.desc', 'Notre système de vendeurs vérifiés garantit qualité et fiabilité dans chaque transaction.', 'about'),
('fr', 'about.features.ai.title', 'Alimenté par IA', 'about'),
('fr', 'about.features.ai.desc', 'Les algorithmes intelligents fournissent détection de fraude, notation de confiance et expérience utilisateur améliorée.', 'about'),
('fr', 'about.features.global.title', 'Accès Global', 'about'),
('fr', 'about.features.global.desc', 'Disponible dans le monde entier avec support pour plusieurs langues et compatibilité réseau Tor.', 'about'),
('fr', 'about.features.privacy.title', 'Confidentialité Complète', 'about'),
('fr', 'about.features.privacy.desc', 'Chiffrement de bout en bout et navigation anonyme assurent que votre identité reste protégée.', 'about'),

-- Shop page (French)
('fr', 'shop.title', 'Marché', 'shop'),
('fr', 'shop.search.placeholder', 'Rechercher des produits...', 'shop'),
('fr', 'shop.filters.category', 'Catégorie', 'shop'),
('fr', 'shop.filters.all_categories', 'Toutes les Catégories', 'shop'),
('fr', 'shop.filters.price_range', 'Gamme de Prix', 'shop'),
('fr', 'shop.filters.all_prices', 'Tous les Prix', 'shop'),
('fr', 'shop.filters.sort_by', 'Trier Par', 'shop'),
('fr', 'shop.filters.newest', 'Plus Récent', 'shop'),
('fr', 'shop.filters.price_low', 'Prix: Croissant', 'shop'),
('fr', 'shop.filters.price_high', 'Prix: Décroissant', 'shop'),
('fr', 'shop.filters.rating', 'Mieux Noté', 'shop'),
('fr', 'shop.top_vendors.title', 'Meilleurs Vendeurs', 'shop'),
('fr', 'shop.trending.title', 'Catégories Tendance', 'shop'),

-- Common UI (French)
('fr', 'ui.search', 'Rechercher', 'ui'),
('fr', 'ui.filter', 'Filtrer', 'ui'),
('fr', 'ui.clear_filters', 'Effacer les Filtres', 'ui'),
('fr', 'ui.no_results', 'Aucun résultat trouvé', 'ui'),
('fr', 'ui.load_more', 'Charger Plus', 'ui'),
('fr', 'ui.view_all', 'Voir Tout', 'ui')

ON CONFLICT (language_code, translation_key, context) DO NOTHING;