-- Add missing translations for German, Italian, Portuguese, Russian, Chinese, Japanese, and Korean
INSERT INTO public.translations (language_code, translation_key, translation_value, context) VALUES

-- GERMAN TRANSLATIONS
-- Footer menu
('de', 'footer.menu.marketplace', 'Marktplatz', 'footer'),
('de', 'footer.menu.browse_products', 'Produkte durchsuchen', 'footer'),
('de', 'footer.menu.verified_vendors', 'Verifizierte Verkäufer', 'footer'),
('de', 'footer.menu.how_to_order', 'Wie bestellen', 'footer'),
('de', 'footer.menu.selling_guide', 'Verkaufsleitfaden', 'footer'),
('de', 'footer.menu.escrow_security', 'Treuhand-Sicherheit', 'footer'),
('de', 'footer.menu.categories', 'Kategorien', 'footer'),
('de', 'footer.menu.support', 'Support', 'footer'),
('de', 'footer.menu.faq', 'FAQ', 'footer'),
('de', 'footer.menu.about_us', 'Über uns', 'footer'),
('de', 'footer.menu.contact', 'Kontakt', 'footer'),
('de', 'footer.menu.forbidden', 'Verboten in Opes Market', 'footer'),
('de', 'footer.menu.pgp_tools', 'PGP-Tools', 'footer'),
('de', 'footer.menu.help_center', 'Hilfezentrum', 'footer'),
('de', 'footer.copyright', '© 2025 OpesMarket. Alle Rechte vorbehalten. Nur-Bitcoin anonymer Marktplatz.', 'footer'),
('de', 'footer.status.secure', 'Sicher • Anonym • KI-gesteuert', 'footer'),
('de', 'footer.status.online', 'Online', 'footer'),

-- About page
('de', 'about.title', 'Über OpesMarket', 'about'),
('de', 'about.subtitle', 'Der sicherste anonyme Marktplatz der Welt, angetrieben von Bitcoin und KI-Technologie.', 'about'),
('de', 'about.mission.title', 'Unsere Mission', 'about'),
('de', 'about.mission.content', 'OpesMarket widmet sich der Schaffung eines sicheren, anonymen und vertrauenswürdigen Marktplatzes, bei dem Privatsphäre oberste Priorität hat. Wir nutzen modernste Bitcoin-Technologie und KI-gesteuerte Sicherheitssysteme, um sichere Transaktionen bei vollständiger Benutzeranonymität zu gewährleisten.', 'about'),
('de', 'about.features.bitcoin.title', 'Nur Bitcoin', 'about'),
('de', 'about.features.bitcoin.desc', 'Alle Transaktionen werden ausschließlich in Bitcoin durchgeführt und gewährleisten vollständige finanzielle Privatsphäre und Dezentralisierung.', 'about'),
('de', 'about.features.security.title', 'Erweiterte Sicherheit', 'about'),
('de', 'about.features.security.desc', 'Mehrschichtige Sicherheitsprotokolle schützen alle Benutzer und Transaktionen vor potenziellen Bedrohungen.', 'about'),
('de', 'about.features.community.title', 'Vertrauensgemeinschaft', 'about'),
('de', 'about.features.community.desc', 'Unser System verifizierter Verkäufer gewährleistet Qualität und Zuverlässigkeit bei jeder Transaktion.', 'about'),
('de', 'about.features.ai.title', 'KI-gesteuert', 'about'),
('de', 'about.features.ai.desc', 'Intelligente Algorithmen bieten Betrugserkennung, Vertrauensbewertung und verbesserte Benutzererfahrung.', 'about'),
('de', 'about.features.global.title', 'Globaler Zugang', 'about'),
('de', 'about.features.global.desc', 'Weltweit verfügbar mit Unterstützung für mehrere Sprachen und Tor-Netzwerk-Kompatibilität.', 'about'),
('de', 'about.features.privacy.title', 'Vollständige Privatsphäre', 'about'),
('de', 'about.features.privacy.desc', 'Ende-zu-Ende-Verschlüsselung und anonymes Browsen stellen sicher, dass Ihre Identität geschützt bleibt.', 'about'),

-- Shop page
('de', 'shop.title', 'Marktplatz', 'shop'),
('de', 'shop.search.placeholder', 'Produkte suchen...', 'shop'),
('de', 'shop.filters.category', 'Kategorie', 'shop'),
('de', 'shop.filters.all_categories', 'Alle Kategorien', 'shop'),
('de', 'shop.filters.price_range', 'Preisbereich', 'shop'),
('de', 'shop.filters.all_prices', 'Alle Preise', 'shop'),
('de', 'shop.filters.sort_by', 'Sortieren nach', 'shop'),
('de', 'shop.filters.newest', 'Neueste', 'shop'),
('de', 'shop.filters.price_low', 'Preis: Niedrig zu Hoch', 'shop'),
('de', 'shop.filters.price_high', 'Preis: Hoch zu Niedrig', 'shop'),
('de', 'shop.filters.rating', 'Am besten bewertet', 'shop'),
('de', 'shop.top_vendors.title', 'Top-Verkäufer', 'shop'),
('de', 'shop.trending.title', 'Trend-Kategorien', 'shop'),

-- Common UI
('de', 'ui.search', 'Suchen', 'ui'),
('de', 'ui.filter', 'Filter', 'ui'),
('de', 'ui.clear_filters', 'Filter löschen', 'ui'),
('de', 'ui.no_results', 'Keine Ergebnisse gefunden', 'ui'),
('de', 'ui.load_more', 'Mehr laden', 'ui'),
('de', 'ui.view_all', 'Alle anzeigen', 'ui'),

-- ITALIAN TRANSLATIONS
-- Footer menu
('it', 'footer.menu.marketplace', 'Marketplace', 'footer'),
('it', 'footer.menu.browse_products', 'Sfoglia Prodotti', 'footer'),
('it', 'footer.menu.verified_vendors', 'Venditori Verificati', 'footer'),
('it', 'footer.menu.how_to_order', 'Come Ordinare', 'footer'),
('it', 'footer.menu.selling_guide', 'Guida alla Vendita', 'footer'),
('it', 'footer.menu.escrow_security', 'Sicurezza Escrow', 'footer'),
('it', 'footer.menu.categories', 'Categorie', 'footer'),
('it', 'footer.menu.support', 'Supporto', 'footer'),
('it', 'footer.menu.faq', 'FAQ', 'footer'),
('it', 'footer.menu.about_us', 'Chi Siamo', 'footer'),
('it', 'footer.menu.contact', 'Contatti', 'footer'),
('it', 'footer.menu.forbidden', 'Vietato in Opes Market', 'footer'),
('it', 'footer.menu.pgp_tools', 'Strumenti PGP', 'footer'),
('it', 'footer.menu.help_center', 'Centro Assistenza', 'footer'),
('it', 'footer.copyright', '© 2025 OpesMarket. Tutti i diritti riservati. Marketplace anonimo solo Bitcoin.', 'footer'),
('it', 'footer.status.secure', 'Sicuro • Anonimo • Alimentato da IA', 'footer'),
('it', 'footer.status.online', 'Online', 'footer'),

-- Shop page
('it', 'shop.title', 'Marketplace', 'shop'),
('it', 'shop.search.placeholder', 'Cerca prodotti...', 'shop'),
('it', 'shop.filters.category', 'Categoria', 'shop'),
('it', 'shop.filters.all_categories', 'Tutte le Categorie', 'shop'),
('it', 'shop.filters.price_range', 'Fascia di Prezzo', 'shop'),
('it', 'shop.filters.all_prices', 'Tutti i Prezzi', 'shop'),
('it', 'shop.filters.sort_by', 'Ordina per', 'shop'),
('it', 'shop.filters.newest', 'Più Recenti', 'shop'),
('it', 'shop.filters.price_low', 'Prezzo: Basso a Alto', 'shop'),
('it', 'shop.filters.price_high', 'Prezzo: Alto a Basso', 'shop'),
('it', 'shop.filters.rating', 'Più Votati', 'shop'),
('it', 'shop.top_vendors.title', 'Top Venditori', 'shop'),
('it', 'shop.trending.title', 'Categorie di Tendenza', 'shop'),

-- Common UI
('it', 'ui.search', 'Cerca', 'ui'),
('it', 'ui.filter', 'Filtra', 'ui'),
('it', 'ui.clear_filters', 'Cancella Filtri', 'ui'),
('it', 'ui.no_results', 'Nessun risultato trovato', 'ui'),
('it', 'ui.load_more', 'Carica Altri', 'ui'),
('it', 'ui.view_all', 'Visualizza Tutto', 'ui'),

-- PORTUGUESE TRANSLATIONS
-- Footer menu
('pt', 'footer.menu.marketplace', 'Mercado', 'footer'),
('pt', 'footer.menu.browse_products', 'Explorar Produtos', 'footer'),
('pt', 'footer.menu.verified_vendors', 'Vendedores Verificados', 'footer'),
('pt', 'footer.menu.how_to_order', 'Como Pedir', 'footer'),
('pt', 'footer.menu.selling_guide', 'Guia de Vendas', 'footer'),
('pt', 'footer.menu.escrow_security', 'Segurança Escrow', 'footer'),
('pt', 'footer.menu.categories', 'Categorias', 'footer'),
('pt', 'footer.menu.support', 'Suporte', 'footer'),
('pt', 'footer.menu.faq', 'FAQ', 'footer'),
('pt', 'footer.menu.about_us', 'Sobre Nós', 'footer'),
('pt', 'footer.menu.contact', 'Contato', 'footer'),
('pt', 'footer.menu.forbidden', 'Proibido no Opes Market', 'footer'),
('pt', 'footer.menu.pgp_tools', 'Ferramentas PGP', 'footer'),
('pt', 'footer.menu.help_center', 'Central de Ajuda', 'footer'),
('pt', 'footer.copyright', '© 2025 OpesMarket. Todos os direitos reservados. Mercado anônimo apenas Bitcoin.', 'footer'),
('pt', 'footer.status.secure', 'Seguro • Anônimo • Alimentado por IA', 'footer'),
('pt', 'footer.status.online', 'Online', 'footer'),

-- Shop page
('pt', 'shop.title', 'Mercado', 'shop'),
('pt', 'shop.search.placeholder', 'Buscar produtos...', 'shop'),
('pt', 'shop.filters.category', 'Categoria', 'shop'),
('pt', 'shop.filters.all_categories', 'Todas as Categorias', 'shop'),
('pt', 'shop.filters.price_range', 'Faixa de Preço', 'shop'),
('pt', 'shop.filters.all_prices', 'Todos os Preços', 'shop'),
('pt', 'shop.filters.sort_by', 'Ordenar por', 'shop'),
('pt', 'shop.filters.newest', 'Mais Novos', 'shop'),
('pt', 'shop.filters.price_low', 'Preço: Menor para Maior', 'shop'),
('pt', 'shop.filters.price_high', 'Preço: Maior para Menor', 'shop'),
('pt', 'shop.filters.rating', 'Mais Bem Avaliados', 'shop'),
('pt', 'shop.top_vendors.title', 'Melhores Vendedores', 'shop'),
('pt', 'shop.trending.title', 'Categorias em Alta', 'shop'),

-- Common UI
('pt', 'ui.search', 'Buscar', 'ui'),
('pt', 'ui.filter', 'Filtrar', 'ui'),
('pt', 'ui.clear_filters', 'Limpar Filtros', 'ui'),
('pt', 'ui.no_results', 'Nenhum resultado encontrado', 'ui'),
('pt', 'ui.load_more', 'Carregar Mais', 'ui'),
('pt', 'ui.view_all', 'Ver Tudo', 'ui'),

-- RUSSIAN TRANSLATIONS
-- Footer menu
('ru', 'footer.menu.marketplace', 'Маркетплейс', 'footer'),
('ru', 'footer.menu.browse_products', 'Просмотр товаров', 'footer'),
('ru', 'footer.menu.verified_vendors', 'Проверенные продавцы', 'footer'),
('ru', 'footer.menu.how_to_order', 'Как заказать', 'footer'),
('ru', 'footer.menu.selling_guide', 'Руководство по продажам', 'footer'),
('ru', 'footer.menu.escrow_security', 'Безопасность эскроу', 'footer'),
('ru', 'footer.menu.categories', 'Категории', 'footer'),
('ru', 'footer.menu.support', 'Поддержка', 'footer'),
('ru', 'footer.menu.faq', 'FAQ', 'footer'),
('ru', 'footer.menu.about_us', 'О нас', 'footer'),
('ru', 'footer.menu.contact', 'Контакты', 'footer'),
('ru', 'footer.menu.forbidden', 'Запрещено в Opes Market', 'footer'),
('ru', 'footer.menu.pgp_tools', 'Инструменты PGP', 'footer'),
('ru', 'footer.menu.help_center', 'Центр помощи', 'footer'),
('ru', 'footer.copyright', '© 2025 OpesMarket. Все права защищены. Анонимный маркетплейс только Bitcoin.', 'footer'),
('ru', 'footer.status.secure', 'Безопасно • Анонимно • ИИ-технологии', 'footer'),
('ru', 'footer.status.online', 'Онлайн', 'footer'),

-- Shop page
('ru', 'shop.title', 'Маркетплейс', 'shop'),
('ru', 'shop.search.placeholder', 'Поиск товаров...', 'shop'),
('ru', 'shop.filters.category', 'Категория', 'shop'),
('ru', 'shop.filters.all_categories', 'Все категории', 'shop'),
('ru', 'shop.filters.price_range', 'Диапазон цен', 'shop'),
('ru', 'shop.filters.all_prices', 'Все цены', 'shop'),
('ru', 'shop.filters.sort_by', 'Сортировать по', 'shop'),
('ru', 'shop.filters.newest', 'Новые', 'shop'),
('ru', 'shop.filters.price_low', 'Цена: по возрастанию', 'shop'),
('ru', 'shop.filters.price_high', 'Цена: по убыванию', 'shop'),
('ru', 'shop.filters.rating', 'Лучший рейтинг', 'shop'),
('ru', 'shop.top_vendors.title', 'Топ продавцов', 'shop'),
('ru', 'shop.trending.title', 'Популярные категории', 'shop'),

-- Common UI
('ru', 'ui.search', 'Поиск', 'ui'),
('ru', 'ui.filter', 'Фильтр', 'ui'),
('ru', 'ui.clear_filters', 'Очистить фильтры', 'ui'),
('ru', 'ui.no_results', 'Результаты не найдены', 'ui'),
('ru', 'ui.load_more', 'Загрузить еще', 'ui'),
('ru', 'ui.view_all', 'Показать все', 'ui'),

-- CHINESE TRANSLATIONS
-- Footer menu
('zh', 'footer.menu.marketplace', '市场', 'footer'),
('zh', 'footer.menu.browse_products', '浏览产品', 'footer'),
('zh', 'footer.menu.verified_vendors', '认证卖家', 'footer'),
('zh', 'footer.menu.how_to_order', '如何下单', 'footer'),
('zh', 'footer.menu.selling_guide', '销售指南', 'footer'),
('zh', 'footer.menu.escrow_security', '托管安全', 'footer'),
('zh', 'footer.menu.categories', '分类', 'footer'),
('zh', 'footer.menu.support', '支持', 'footer'),
('zh', 'footer.menu.faq', '常见问题', 'footer'),
('zh', 'footer.menu.about_us', '关于我们', 'footer'),
('zh', 'footer.menu.contact', '联系我们', 'footer'),
('zh', 'footer.menu.forbidden', '在Opes Market中禁止', 'footer'),
('zh', 'footer.menu.pgp_tools', 'PGP工具', 'footer'),
('zh', 'footer.menu.help_center', '帮助中心', 'footer'),
('zh', 'footer.copyright', '© 2025 OpesMarket。保留所有权利。仅限比特币匿名市场。', 'footer'),
('zh', 'footer.status.secure', '安全 • 匿名 • AI驱动', 'footer'),
('zh', 'footer.status.online', '在线', 'footer'),

-- Shop page
('zh', 'shop.title', '市场', 'shop'),
('zh', 'shop.search.placeholder', '搜索产品...', 'shop'),
('zh', 'shop.filters.category', '分类', 'shop'),
('zh', 'shop.filters.all_categories', '所有分类', 'shop'),
('zh', 'shop.filters.price_range', '价格范围', 'shop'),
('zh', 'shop.filters.all_prices', '所有价格', 'shop'),
('zh', 'shop.filters.sort_by', '排序', 'shop'),
('zh', 'shop.filters.newest', '最新', 'shop'),
('zh', 'shop.filters.price_low', '价格：从低到高', 'shop'),
('zh', 'shop.filters.price_high', '价格：从高到低', 'shop'),
('zh', 'shop.filters.rating', '评分最高', 'shop'),
('zh', 'shop.top_vendors.title', '顶级卖家', 'shop'),
('zh', 'shop.trending.title', '热门分类', 'shop'),

-- Common UI
('zh', 'ui.search', '搜索', 'ui'),
('zh', 'ui.filter', '筛选', 'ui'),
('zh', 'ui.clear_filters', '清除筛选', 'ui'),
('zh', 'ui.no_results', '未找到结果', 'ui'),
('zh', 'ui.load_more', '加载更多', 'ui'),
('zh', 'ui.view_all', '查看全部', 'ui'),

-- JAPANESE TRANSLATIONS
-- Footer menu
('ja', 'footer.menu.marketplace', 'マーケットプレイス', 'footer'),
('ja', 'footer.menu.browse_products', '商品を見る', 'footer'),
('ja', 'footer.menu.verified_vendors', '認証済み販売者', 'footer'),
('ja', 'footer.menu.how_to_order', '注文方法', 'footer'),
('ja', 'footer.menu.selling_guide', '販売ガイド', 'footer'),
('ja', 'footer.menu.escrow_security', 'エスクローセキュリティ', 'footer'),
('ja', 'footer.menu.categories', 'カテゴリ', 'footer'),
('ja', 'footer.menu.support', 'サポート', 'footer'),
('ja', 'footer.menu.faq', 'よくある質問', 'footer'),
('ja', 'footer.menu.about_us', '私たちについて', 'footer'),
('ja', 'footer.menu.contact', 'お問い合わせ', 'footer'),
('ja', 'footer.menu.forbidden', 'Opes Marketで禁止', 'footer'),
('ja', 'footer.menu.pgp_tools', 'PGPツール', 'footer'),
('ja', 'footer.menu.help_center', 'ヘルプセンター', 'footer'),
('ja', 'footer.copyright', '© 2025 OpesMarket。すべての権利を保有。ビットコインのみ匿名マーケットプレイス。', 'footer'),
('ja', 'footer.status.secure', 'セキュア • 匿名 • AI搭載', 'footer'),
('ja', 'footer.status.online', 'オンライン', 'footer'),

-- Shop page
('ja', 'shop.title', 'マーケットプレイス', 'shop'),
('ja', 'shop.search.placeholder', '商品を検索...', 'shop'),
('ja', 'shop.filters.category', 'カテゴリ', 'shop'),
('ja', 'shop.filters.all_categories', 'すべてのカテゴリ', 'shop'),
('ja', 'shop.filters.price_range', '価格帯', 'shop'),
('ja', 'shop.filters.all_prices', 'すべての価格', 'shop'),
('ja', 'shop.filters.sort_by', '並び替え', 'shop'),
('ja', 'shop.filters.newest', '新着順', 'shop'),
('ja', 'shop.filters.price_low', '価格：安い順', 'shop'),
('ja', 'shop.filters.price_high', '価格：高い順', 'shop'),
('ja', 'shop.filters.rating', '評価順', 'shop'),
('ja', 'shop.top_vendors.title', 'トップ販売者', 'shop'),
('ja', 'shop.trending.title', 'トレンドカテゴリ', 'shop'),

-- Common UI
('ja', 'ui.search', '検索', 'ui'),
('ja', 'ui.filter', 'フィルター', 'ui'),
('ja', 'ui.clear_filters', 'フィルターをクリア', 'ui'),
('ja', 'ui.no_results', '結果が見つかりません', 'ui'),
('ja', 'ui.load_more', 'もっと読み込む', 'ui'),
('ja', 'ui.view_all', 'すべて表示', 'ui'),

-- KOREAN TRANSLATIONS
-- Footer menu
('ko', 'footer.menu.marketplace', '마켓플레이스', 'footer'),
('ko', 'footer.menu.browse_products', '상품 둘러보기', 'footer'),
('ko', 'footer.menu.verified_vendors', '검증된 판매자', 'footer'),
('ko', 'footer.menu.how_to_order', '주문 방법', 'footer'),
('ko', 'footer.menu.selling_guide', '판매 가이드', 'footer'),
('ko', 'footer.menu.escrow_security', '에스크로 보안', 'footer'),
('ko', 'footer.menu.categories', '카테고리', 'footer'),
('ko', 'footer.menu.support', '지원', 'footer'),
('ko', 'footer.menu.faq', '자주 묻는 질문', 'footer'),
('ko', 'footer.menu.about_us', '회사 소개', 'footer'),
('ko', 'footer.menu.contact', '연락처', 'footer'),
('ko', 'footer.menu.forbidden', 'Opes Market에서 금지됨', 'footer'),
('ko', 'footer.menu.pgp_tools', 'PGP 도구', 'footer'),
('ko', 'footer.menu.help_center', '도움말 센터', 'footer'),
('ko', 'footer.copyright', '© 2025 OpesMarket. 모든 권리 보유. 비트코인 전용 익명 마켓플레이스.', 'footer'),
('ko', 'footer.status.secure', '보안 • 익명 • AI 기반', 'footer'),
('ko', 'footer.status.online', '온라인', 'footer'),

-- Shop page
('ko', 'shop.title', '마켓플레이스', 'shop'),
('ko', 'shop.search.placeholder', '상품 검색...', 'shop'),
('ko', 'shop.filters.category', '카테고리', 'shop'),
('ko', 'shop.filters.all_categories', '모든 카테고리', 'shop'),
('ko', 'shop.filters.price_range', '가격 범위', 'shop'),
('ko', 'shop.filters.all_prices', '모든 가격', 'shop'),
('ko', 'shop.filters.sort_by', '정렬', 'shop'),
('ko', 'shop.filters.newest', '최신순', 'shop'),
('ko', 'shop.filters.price_low', '가격: 낮은순', 'shop'),
('ko', 'shop.filters.price_high', '가격: 높은순', 'shop'),
('ko', 'shop.filters.rating', '평점순', 'shop'),
('ko', 'shop.top_vendors.title', '인기 판매자', 'shop'),
('ko', 'shop.trending.title', '인기 카테고리', 'shop'),

-- Common UI
('ko', 'ui.search', '검색', 'ui'),
('ko', 'ui.filter', '필터', 'ui'),
('ko', 'ui.clear_filters', '필터 지우기', 'ui'),
('ko', 'ui.no_results', '결과를 찾을 수 없습니다', 'ui'),
('ko', 'ui.load_more', '더 보기', 'ui'),
('ko', 'ui.view_all', '모두 보기', 'ui')

ON CONFLICT (language_code, translation_key, context) DO NOTHING;