-- Add missing translation keys and complete translation coverage for all languages
-- Using ON CONFLICT to handle existing keys

INSERT INTO public.translations (language_code, translation_key, translation_value, context) VALUES

-- Missing English translations
('en', 'footer.description', 'The world''s most secure anonymous marketplace. Trade with confidence using Bitcoin, verified vendors, and AI-powered security systems.', 'footer'),
('en', 'footer.encrypted', 'End-to-End Encrypted', 'footer'),
('en', 'footer.ai_powered', 'AI-Powered', 'footer'),
('en', 'featured_vendors.title', 'Featured Vendors', 'featured_vendors'),
('en', 'featured_vendors.subtitle', 'Discover our top-rated, verified vendors with proven track records and high trust scores. All vendors have posted their $250 annual bond for your protection.', 'featured_vendors'),
('en', 'featured_vendors.view_all', 'View All Verified Vendors', 'featured_vendors'),

-- Missing Spanish translations  
('es', 'footer.description', 'El mercado anónimo más seguro del mundo. Comercia con confianza usando Bitcoin, vendedores verificados y sistemas de seguridad impulsados por IA.', 'footer'),
('es', 'footer.encrypted', 'Cifrado de Extremo a Extremo', 'footer'),
('es', 'footer.ai_powered', 'Impulsado por IA', 'footer'),
('es', 'featured_vendors.title', 'Vendedores Destacados', 'featured_vendors'),
('es', 'featured_vendors.subtitle', 'Descubre nuestros vendedores mejor calificados y verificados con historiales comprobados y altas puntuaciones de confianza. Todos los vendedores han depositado su fianza anual de $250 para tu protección.', 'featured_vendors'),
('es', 'featured_vendors.view_all', 'Ver Todos los Vendedores Verificados', 'featured_vendors'),

-- Missing French translations
('fr', 'footer.description', 'Le marché anonyme le plus sécurisé au monde. Commercez en toute confiance avec Bitcoin, des vendeurs vérifiés et des systèmes de sécurité alimentés par l''IA.', 'footer'),
('fr', 'footer.encrypted', 'Chiffrement de Bout en Bout', 'footer'),
('fr', 'footer.ai_powered', 'Alimenté par l''IA', 'footer'),
('fr', 'featured_vendors.title', 'Vendeurs en Vedette', 'featured_vendors'),
('fr', 'featured_vendors.subtitle', 'Découvrez nos vendeurs les mieux notés et vérifiés avec des antécédents prouvés et des scores de confiance élevés. Tous les vendeurs ont déposé leur caution annuelle de 250$ pour votre protection.', 'featured_vendors'),
('fr', 'featured_vendors.view_all', 'Voir Tous les Vendeurs Vérifiés', 'featured_vendors'),

-- German translations (complete new language)
('de', 'hero.title.ai_powered', 'KI-gesteuert', 'hero'),
('de', 'hero.title.anonymous_marketplace', 'Anonymer Marktplatz', 'hero'),
('de', 'hero.subtitle', 'Handeln Sie sicher mit reinen Bitcoin-Transaktionen, verifizierten Verkäufern und KI-gesteuerten Vertrauensbewertungen. Ihre Privatsphäre ist unsere Priorität.', 'hero'),
('de', 'hero.cta.start_shopping', 'Einkaufen Beginnen', 'hero'),
('de', 'hero.cta.become_vendor', 'Verkäufer Werden', 'hero'),
('de', 'hero.feature.bitcoin_only', 'Nur Bitcoin', 'hero'),
('de', 'hero.feature.bitcoin_desc', 'Sichere, private Transaktionen mit integriertem Treuhandservice', 'hero'),
('de', 'hero.feature.verified_vendors', 'Verifizierte Verkäufer', 'hero'),
('de', 'hero.feature.verified_desc', '250$ Jahreskaution gewährleistet Qualität und Verantwortlichkeit', 'hero'),
('de', 'hero.feature.ai_powered', 'KI-gesteuert', 'hero'),
('de', 'hero.feature.ai_desc', 'Intelligente Betrugserkennung und dynamische Vertrauensbewertung', 'hero'),
('de', 'hero.feature.anonymous', 'Anonym', 'hero'),
('de', 'hero.feature.anonymous_desc', 'Ende-zu-Ende-Verschlüsselung mit optionaler Tor-Unterstützung', 'hero'),
('de', 'nav.shop', 'Shop', 'nav'),
('de', 'nav.login', 'Anmelden', 'nav'),
('de', 'nav.logout', 'Abmelden', 'nav'),
('de', 'nav.become_vendor', 'Verkäufer Werden', 'nav'),
('de', 'nav.forum', 'Forum', 'nav'),
('de', 'nav.wishlist', 'Wunschliste', 'nav'),
('de', 'nav.profile', 'Profil', 'nav'),
('de', 'nav.orders', 'Meine Bestellungen', 'nav'),
('de', 'nav.messages', 'Nachrichten', 'nav'),
('de', 'nav.affiliate', 'Affiliate', 'nav'),
('de', 'nav.home', 'Startseite', 'nav'),
('de', 'nav.products', 'Produkte', 'nav'),
('de', 'nav.vendors', 'Verkäufer', 'nav'),
('de', 'footer.description', 'Der sicherste anonyme Marktplatz der Welt. Handeln Sie vertrauensvoll mit Bitcoin, verifizierten Verkäufern und KI-gesteuerten Sicherheitssystemen.', 'footer'),
('de', 'footer.encrypted', 'Ende-zu-Ende-Verschlüsselt', 'footer'),
('de', 'footer.ai_powered', 'KI-gesteuert', 'footer'),
('de', 'vendor.verified', 'Verifizierte Verkäufer', 'vendor'),
('de', 'vendor.trust_score', 'Vertrauensscore', 'vendor'),
('de', 'product.add_to_wishlist', 'Zur Wunschliste Hinzufügen', 'product'),
('de', 'product.buy_now', 'Jetzt Kaufen', 'product'),
('de', 'product.out_of_stock', 'Ausverkauft', 'product'),
('de', 'featured_vendors.title', 'Empfohlene Verkäufer', 'featured_vendors'),
('de', 'featured_vendors.subtitle', 'Entdecken Sie unsere bestbewerteten, verifizierten Verkäufer mit nachgewiesener Erfolgsbilanz und hohen Vertrauenswerten. Alle Verkäufer haben ihre jährliche Kaution von 250$ für Ihren Schutz hinterlegt.', 'featured_vendors'),
('de', 'featured_vendors.view_all', 'Alle Verifizierten Verkäufer Anzeigen', 'featured_vendors'),
('de', 'common.loading', 'Lädt...', 'common'),
('de', 'common.error', 'Fehler', 'common'),
('de', 'common.success', 'Erfolg', 'common'),
('de', 'common.cancel', 'Abbrechen', 'common'),
('de', 'common.save', 'Speichern', 'common'),
('de', 'common.delete', 'Löschen', 'common'),
('de', 'common.edit', 'Bearbeiten', 'common'),
('de', 'common.search', 'Suchen', 'common'),
('de', 'common.filter', 'Filter', 'common'),

-- Italian translations (complete new language)
('it', 'hero.title.ai_powered', 'Alimentato dall''IA', 'hero'),
('it', 'hero.title.anonymous_marketplace', 'Mercato Anonimo', 'hero'),
('it', 'hero.subtitle', 'Commercia in sicurezza con transazioni solo Bitcoin, venditori verificati e punteggi di fiducia guidati dall''IA. La tua privacy è la nostra priorità.', 'hero'),
('it', 'hero.cta.start_shopping', 'Inizia a Comprare', 'hero'),
('it', 'hero.cta.become_vendor', 'Diventa Venditore', 'hero'),
('it', 'hero.feature.bitcoin_only', 'Solo Bitcoin', 'hero'),
('it', 'hero.feature.bitcoin_desc', 'Transazioni sicure e private con escrow integrato', 'hero'),
('it', 'hero.feature.verified_vendors', 'Venditori Verificati', 'hero'),
('it', 'hero.feature.verified_desc', 'Cauzione annuale di $250 garantisce qualità e responsabilità', 'hero'),
('it', 'hero.feature.ai_powered', 'Alimentato dall''IA', 'hero'),
('it', 'hero.feature.ai_desc', 'Rilevamento intelligente delle frodi e punteggio di fiducia dinamico', 'hero'),
('it', 'hero.feature.anonymous', 'Anonimo', 'hero'),
('it', 'hero.feature.anonymous_desc', 'Crittografia end-to-end con supporto Tor opzionale', 'hero'),
('it', 'nav.shop', 'Negozio', 'nav'),
('it', 'nav.login', 'Accedi', 'nav'),
('it', 'nav.logout', 'Esci', 'nav'),
('it', 'nav.become_vendor', 'Diventa Venditore', 'nav'),
('it', 'nav.forum', 'Forum', 'nav'),
('it', 'nav.wishlist', 'Lista Desideri', 'nav'),
('it', 'nav.profile', 'Profilo', 'nav'),
('it', 'nav.orders', 'I Miei Ordini', 'nav'),
('it', 'nav.messages', 'Messaggi', 'nav'),
('it', 'nav.affiliate', 'Affiliato', 'nav'),
('it', 'nav.home', 'Home', 'nav'),
('it', 'nav.products', 'Prodotti', 'nav'),
('it', 'nav.vendors', 'Venditori', 'nav'),
('it', 'footer.description', 'Il mercato anonimo più sicuro al mondo. Commercia con fiducia usando Bitcoin, venditori verificati e sistemi di sicurezza alimentati dall''IA.', 'footer'),
('it', 'footer.encrypted', 'Crittografato End-to-End', 'footer'),
('it', 'footer.ai_powered', 'Alimentato dall''IA', 'footer'),
('it', 'vendor.verified', 'Venditori Verificati', 'vendor'),
('it', 'vendor.trust_score', 'Punteggio di Fiducia', 'vendor'),
('it', 'product.add_to_wishlist', 'Aggiungi alla Lista Desideri', 'product'),
('it', 'product.buy_now', 'Compra Ora', 'product'),
('it', 'product.out_of_stock', 'Esaurito', 'product'),
('it', 'featured_vendors.title', 'Venditori in Primo Piano', 'featured_vendors'),
('it', 'featured_vendors.subtitle', 'Scopri i nostri venditori più quotati e verificati con track record comprovati e alti punteggi di fiducia. Tutti i venditori hanno depositato la loro cauzione annuale di $250 per la tua protezione.', 'featured_vendors'),
('it', 'featured_vendors.view_all', 'Visualizza Tutti i Venditori Verificati', 'featured_vendors'),
('it', 'common.loading', 'Caricamento...', 'common'),
('it', 'common.error', 'Errore', 'common'),
('it', 'common.success', 'Successo', 'common'),
('it', 'common.cancel', 'Annulla', 'common'),
('it', 'common.save', 'Salva', 'common'),
('it', 'common.delete', 'Elimina', 'common'),
('it', 'common.edit', 'Modifica', 'common'),
('it', 'common.search', 'Cerca', 'common'),
('it', 'common.filter', 'Filtro', 'common'),

-- Portuguese translations (complete new language)
('pt', 'hero.title.ai_powered', 'Alimentado por IA', 'hero'),
('pt', 'hero.title.anonymous_marketplace', 'Mercado Anônimo', 'hero'),
('pt', 'hero.subtitle', 'Negocie com segurança com transações apenas em Bitcoin, vendedores verificados e pontuação de confiança orientada por IA. Sua privacidade é nossa prioridade.', 'hero'),
('pt', 'hero.cta.start_shopping', 'Começar a Comprar', 'hero'),
('pt', 'hero.cta.become_vendor', 'Tornar-se Vendedor', 'hero'),
('pt', 'hero.feature.bitcoin_only', 'Apenas Bitcoin', 'hero'),
('pt', 'hero.feature.bitcoin_desc', 'Transações seguras e privadas com custódia integrada', 'hero'),
('pt', 'hero.feature.verified_vendors', 'Vendedores Verificados', 'hero'),
('pt', 'hero.feature.verified_desc', 'Garantia anual de $250 assegura qualidade e responsabilidade', 'hero'),
('pt', 'hero.feature.ai_powered', 'Alimentado por IA', 'hero'),
('pt', 'hero.feature.ai_desc', 'Detecção inteligente de fraudes e pontuação dinâmica de confiança', 'hero'),
('pt', 'hero.feature.anonymous', 'Anônimo', 'hero'),
('pt', 'hero.feature.anonymous_desc', 'Criptografia ponta-a-ponta com suporte opcional ao Tor', 'hero'),
('pt', 'nav.shop', 'Loja', 'nav'),
('pt', 'nav.login', 'Entrar', 'nav'),
('pt', 'nav.logout', 'Sair', 'nav'),
('pt', 'nav.become_vendor', 'Tornar-se Vendedor', 'nav'),
('pt', 'nav.forum', 'Fórum', 'nav'),
('pt', 'nav.wishlist', 'Lista de Desejos', 'nav'),
('pt', 'nav.profile', 'Perfil', 'nav'),
('pt', 'nav.orders', 'Meus Pedidos', 'nav'),
('pt', 'nav.messages', 'Mensagens', 'nav'),
('pt', 'nav.affiliate', 'Afiliado', 'nav'),
('pt', 'nav.home', 'Início', 'nav'),
('pt', 'nav.products', 'Produtos', 'nav'),
('pt', 'nav.vendors', 'Vendedores', 'nav'),
('pt', 'footer.description', 'O mercado anônimo mais seguro do mundo. Negocie com confiança usando Bitcoin, vendedores verificados e sistemas de segurança alimentados por IA.', 'footer'),
('pt', 'footer.encrypted', 'Criptografado Ponta-a-Ponta', 'footer'),
('pt', 'footer.ai_powered', 'Alimentado por IA', 'footer'),
('pt', 'vendor.verified', 'Vendedores Verificados', 'vendor'),
('pt', 'vendor.trust_score', 'Pontuação de Confiança', 'vendor'),
('pt', 'product.add_to_wishlist', 'Adicionar à Lista de Desejos', 'product'),
('pt', 'product.buy_now', 'Comprar Agora', 'product'),
('pt', 'product.out_of_stock', 'Fora de Estoque', 'product'),
('pt', 'featured_vendors.title', 'Vendedores em Destaque', 'featured_vendors'),
('pt', 'featured_vendors.subtitle', 'Descubra nossos vendedores mais bem avaliados e verificados com histórico comprovado e altas pontuações de confiança. Todos os vendedores depositaram sua garantia anual de $250 para sua proteção.', 'featured_vendors'),
('pt', 'featured_vendors.view_all', 'Ver Todos os Vendedores Verificados', 'featured_vendors'),
('pt', 'common.loading', 'Carregando...', 'common'),
('pt', 'common.error', 'Erro', 'common'),
('pt', 'common.success', 'Sucesso', 'common'),
('pt', 'common.cancel', 'Cancelar', 'common'),
('pt', 'common.save', 'Salvar', 'common'),
('pt', 'common.delete', 'Excluir', 'common'),
('pt', 'common.edit', 'Editar', 'common'),
('pt', 'common.search', 'Pesquisar', 'common'),
('pt', 'common.filter', 'Filtro', 'common'),

-- Russian translations (complete new language)
('ru', 'hero.title.ai_powered', 'С поддержкой ИИ', 'hero'),
('ru', 'hero.title.anonymous_marketplace', 'Анонимная торговая площадка', 'hero'),
('ru', 'hero.subtitle', 'Торгуйте безопасно с транзакциями только в Bitcoin, проверенными продавцами и оценкой доверия на основе ИИ. Ваша конфиденциальность - наш приоритет.', 'hero'),
('ru', 'hero.cta.start_shopping', 'Начать покупки', 'hero'),
('ru', 'hero.cta.become_vendor', 'Стать продавцом', 'hero'),
('ru', 'hero.feature.bitcoin_only', 'Только Bitcoin', 'hero'),
('ru', 'hero.feature.bitcoin_desc', 'Безопасные, приватные транзакции со встроенным эскроу', 'hero'),
('ru', 'hero.feature.verified_vendors', 'Проверенные продавцы', 'hero'),
('ru', 'hero.feature.verified_desc', 'Годовой залог $250 обеспечивает качество и ответственность', 'hero'),
('ru', 'hero.feature.ai_powered', 'С поддержкой ИИ', 'hero'),
('ru', 'hero.feature.ai_desc', 'Умное обнаружение мошенничества и динамическая оценка доверия', 'hero'),
('ru', 'hero.feature.anonymous', 'Анонимно', 'hero'),
('ru', 'hero.feature.anonymous_desc', 'Сквозное шифрование с опциональной поддержкой Tor', 'hero'),
('ru', 'nav.shop', 'Магазин', 'nav'),
('ru', 'nav.login', 'Войти', 'nav'),
('ru', 'nav.logout', 'Выйти', 'nav'),
('ru', 'nav.become_vendor', 'Стать продавцом', 'nav'),
('ru', 'nav.forum', 'Форум', 'nav'),
('ru', 'nav.wishlist', 'Избранное', 'nav'),
('ru', 'nav.profile', 'Профиль', 'nav'),
('ru', 'nav.orders', 'Мои заказы', 'nav'),
('ru', 'nav.messages', 'Сообщения', 'nav'),
('ru', 'nav.affiliate', 'Партнёрство', 'nav'),
('ru', 'nav.home', 'Главная', 'nav'),
('ru', 'nav.products', 'Товары', 'nav'),
('ru', 'nav.vendors', 'Продавцы', 'nav'),
('ru', 'footer.description', 'Самая безопасная анонимная торговая площадка в мире. Торгуйте с уверенностью, используя Bitcoin, проверенных продавцов и системы безопасности на основе ИИ.', 'footer'),
('ru', 'footer.encrypted', 'Сквозное шифрование', 'footer'),
('ru', 'footer.ai_powered', 'С поддержкой ИИ', 'footer'),
('ru', 'vendor.verified', 'Проверенные продавцы', 'vendor'),
('ru', 'vendor.trust_score', 'Оценка доверия', 'vendor'),
('ru', 'product.add_to_wishlist', 'Добавить в избранное', 'product'),
('ru', 'product.buy_now', 'Купить сейчас', 'product'),
('ru', 'product.out_of_stock', 'Нет в наличии', 'product'),
('ru', 'featured_vendors.title', 'Рекомендуемые продавцы', 'featured_vendors'),
('ru', 'featured_vendors.subtitle', 'Откройте для себя наших лучших проверенных продавцов с доказанной репутацией и высокими оценками доверия. Все продавцы внесли годовой залог $250 для вашей защиты.', 'featured_vendors'),
('ru', 'featured_vendors.view_all', 'Посмотреть всех проверенных продавцов', 'featured_vendors'),
('ru', 'common.loading', 'Загрузка...', 'common'),
('ru', 'common.error', 'Ошибка', 'common'),
('ru', 'common.success', 'Успех', 'common'),
('ru', 'common.cancel', 'Отмена', 'common'),
('ru', 'common.save', 'Сохранить', 'common'),
('ru', 'common.delete', 'Удалить', 'common'),
('ru', 'common.edit', 'Редактировать', 'common'),
('ru', 'common.search', 'Поиск', 'common'),
('ru', 'common.filter', 'Фильтр', 'common'),

-- Chinese translations (complete new language)
('zh', 'hero.title.ai_powered', 'AI驱动', 'hero'),
('zh', 'hero.title.anonymous_marketplace', '匿名市场', 'hero'),
('zh', 'hero.subtitle', '通过仅限比特币交易、经过验证的卖家和AI驱动的信任评分安全交易。您的隐私是我们的首要任务。', 'hero'),
('zh', 'hero.cta.start_shopping', '开始购物', 'hero'),
('zh', 'hero.cta.become_vendor', '成为卖家', 'hero'),
('zh', 'hero.feature.bitcoin_only', '仅比特币', 'hero'),
('zh', 'hero.feature.bitcoin_desc', '安全、私密的交易，内置托管服务', 'hero'),
('zh', 'hero.feature.verified_vendors', '认证卖家', 'hero'),
('zh', 'hero.feature.verified_desc', '250美元年度保证金确保质量和责任', 'hero'),
('zh', 'hero.feature.ai_powered', 'AI驱动', 'hero'),
('zh', 'hero.feature.ai_desc', '智能欺诈检测和动态信任评分', 'hero'),
('zh', 'hero.feature.anonymous', '匿名', 'hero'),
('zh', 'hero.feature.anonymous_desc', '端到端加密，可选Tor支持', 'hero'),
('zh', 'nav.shop', '商店', 'nav'),
('zh', 'nav.login', '登录', 'nav'),
('zh', 'nav.logout', '退出', 'nav'),
('zh', 'nav.become_vendor', '成为卖家', 'nav'),
('zh', 'nav.forum', '论坛', 'nav'),
('zh', 'nav.wishlist', '心愿单', 'nav'),
('zh', 'nav.profile', '个人资料', 'nav'),
('zh', 'nav.orders', '我的订单', 'nav'),
('zh', 'nav.messages', '消息', 'nav'),
('zh', 'nav.affiliate', '联盟', 'nav'),
('zh', 'nav.home', '首页', 'nav'),
('zh', 'nav.products', '产品', 'nav'),
('zh', 'nav.vendors', '卖家', 'nav'),
('zh', 'footer.description', '世界上最安全的匿名市场。使用比特币、认证卖家和AI驱动的安全系统放心交易。', 'footer'),
('zh', 'footer.encrypted', '端到端加密', 'footer'),
('zh', 'footer.ai_powered', 'AI驱动', 'footer'),
('zh', 'vendor.verified', '认证卖家', 'vendor'),
('zh', 'vendor.trust_score', '信任评分', 'vendor'),
('zh', 'product.add_to_wishlist', '添加到心愿单', 'product'),
('zh', 'product.buy_now', '立即购买', 'product'),
('zh', 'product.out_of_stock', '缺货', 'product'),
('zh', 'featured_vendors.title', '精选卖家', 'featured_vendors'),
('zh', 'featured_vendors.subtitle', '发现我们评分最高的认证卖家，他们拥有良好的记录和高信任评分。所有卖家都已缴纳250美元年度保证金以保护您。', 'featured_vendors'),
('zh', 'featured_vendors.view_all', '查看所有认证卖家', 'featured_vendors'),
('zh', 'common.loading', '加载中...', 'common'),
('zh', 'common.error', '错误', 'common'),
('zh', 'common.success', '成功', 'common'),
('zh', 'common.cancel', '取消', 'common'),
('zh', 'common.save', '保存', 'common'),
('zh', 'common.delete', '删除', 'common'),
('zh', 'common.edit', '编辑', 'common'),
('zh', 'common.search', '搜索', 'common'),
('zh', 'common.filter', '筛选', 'common'),

-- Japanese translations (complete new language)
('ja', 'hero.title.ai_powered', 'AI搭載', 'hero'),
('ja', 'hero.title.anonymous_marketplace', '匿名マーケットプレイス', 'hero'),
('ja', 'hero.subtitle', 'ビットコインのみの取引、認証された販売者、AI主導の信頼スコアで安全に取引。あなたのプライバシーが私たちの優先事項です。', 'hero'),
('ja', 'hero.cta.start_shopping', 'ショッピングを開始', 'hero'),
('ja', 'hero.cta.become_vendor', '販売者になる', 'hero'),
('ja', 'hero.feature.bitcoin_only', 'ビットコインのみ', 'hero'),
('ja', 'hero.feature.bitcoin_desc', '組み込みエスクローによる安全でプライベートな取引', 'hero'),
('ja', 'hero.feature.verified_vendors', '認証済み販売者', 'hero'),
('ja', 'hero.feature.verified_desc', '年間250ドルの保証金が品質と責任を保証', 'hero'),
('ja', 'hero.feature.ai_powered', 'AI搭載', 'hero'),
('ja', 'hero.feature.ai_desc', 'スマートな詐欺検出と動的信頼スコア', 'hero'),
('ja', 'hero.feature.anonymous', '匿名', 'hero'),
('ja', 'hero.feature.anonymous_desc', 'エンドツーエンド暗号化とオプションのTorサポート', 'hero'),
('ja', 'nav.shop', 'ショップ', 'nav'),
('ja', 'nav.login', 'ログイン', 'nav'),
('ja', 'nav.logout', 'ログアウト', 'nav'),
('ja', 'nav.become_vendor', '販売者になる', 'nav'),
('ja', 'nav.forum', 'フォーラム', 'nav'),
('ja', 'nav.wishlist', 'ウィッシュリスト', 'nav'),
('ja', 'nav.profile', 'プロフィール', 'nav'),
('ja', 'nav.orders', 'マイオーダー', 'nav'),
('ja', 'nav.messages', 'メッセージ', 'nav'),
('ja', 'nav.affiliate', 'アフィリエイト', 'nav'),
('ja', 'nav.home', 'ホーム', 'nav'),
('ja', 'nav.products', '商品', 'nav'),
('ja', 'nav.vendors', '販売者', 'nav'),
('ja', 'footer.description', '世界で最も安全な匿名マーケットプレイス。ビットコイン、認証済み販売者、AI搭載セキュリティシステムで安心して取引。', 'footer'),
('ja', 'footer.encrypted', 'エンドツーエンド暗号化', 'footer'),
('ja', 'footer.ai_powered', 'AI搭載', 'footer'),
('ja', 'vendor.verified', '認証済み販売者', 'vendor'),
('ja', 'vendor.trust_score', '信頼スコア', 'vendor'),
('ja', 'product.add_to_wishlist', 'ウィッシュリストに追加', 'product'),
('ja', 'product.buy_now', '今すぐ購入', 'product'),
('ja', 'product.out_of_stock', '在庫切れ', 'product'),
('ja', 'featured_vendors.title', '注目の販売者', 'featured_vendors'),
('ja', 'featured_vendors.subtitle', '実績があり高い信頼スコアを持つ、最高評価の認証済み販売者をご覧ください。すべての販売者があなたの保護のために年間250ドルの保証金を預けています。', 'featured_vendors'),
('ja', 'featured_vendors.view_all', 'すべての認証済み販売者を見る', 'featured_vendors'),
('ja', 'common.loading', '読み込み中...', 'common'),
('ja', 'common.error', 'エラー', 'common'),
('ja', 'common.success', '成功', 'common'),
('ja', 'common.cancel', 'キャンセル', 'common'),
('ja', 'common.save', '保存', 'common'),
('ja', 'common.delete', '削除', 'common'),
('ja', 'common.edit', '編集', 'common'),
('ja', 'common.search', '検索', 'common'),
('ja', 'common.filter', 'フィルター', 'common'),

-- Korean translations (complete new language)
('ko', 'hero.title.ai_powered', 'AI 기반', 'hero'),
('ko', 'hero.title.anonymous_marketplace', '익명 마켓플레이스', 'hero'),
('ko', 'hero.subtitle', '비트코인 전용 거래, 검증된 판매자, AI 기반 신뢰 점수로 안전하게 거래하세요. 귀하의 개인정보 보호가 저희의 우선순위입니다.', 'hero'),
('ko', 'hero.cta.start_shopping', '쇼핑 시작', 'hero'),
('ko', 'hero.cta.become_vendor', '판매자 되기', 'hero'),
('ko', 'hero.feature.bitcoin_only', '비트코인 전용', 'hero'),
('ko', 'hero.feature.bitcoin_desc', '내장 에스크로가 있는 안전하고 개인적인 거래', 'hero'),
('ko', 'hero.feature.verified_vendors', '검증된 판매자', 'hero'),
('ko', 'hero.feature.verified_desc', '연간 $250 보증금이 품질과 책임을 보장', 'hero'),
('ko', 'hero.feature.ai_powered', 'AI 기반', 'hero'),
('ko', 'hero.feature.ai_desc', '스마트 사기 탐지 및 동적 신뢰 점수', 'hero'),
('ko', 'hero.feature.anonymous', '익명', 'hero'),
('ko', 'hero.feature.anonymous_desc', '선택적 Tor 지원이 있는 종단간 암호화', 'hero'),
('ko', 'nav.shop', '쇼핑', 'nav'),
('ko', 'nav.login', '로그인', 'nav'),
('ko', 'nav.logout', '로그아웃', 'nav'),
('ko', 'nav.become_vendor', '판매자 되기', 'nav'),
('ko', 'nav.forum', '포럼', 'nav'),
('ko', 'nav.wishlist', '위시리스트', 'nav'),
('ko', 'nav.profile', '프로필', 'nav'),
('ko', 'nav.orders', '내 주문', 'nav'),
('ko', 'nav.messages', '메시지', 'nav'),
('ko', 'nav.affiliate', '제휴', 'nav'),
('ko', 'nav.home', '홈', 'nav'),
('ko', 'nav.products', '상품', 'nav'),
('ko', 'nav.vendors', '판매자', 'nav'),
('ko', 'footer.description', '세계에서 가장 안전한 익명 마켓플레이스. 비트코인, 검증된 판매자, AI 기반 보안 시스템으로 안심하고 거래하세요.', 'footer'),
('ko', 'footer.encrypted', '종단간 암호화', 'footer'),
('ko', 'footer.ai_powered', 'AI 기반', 'footer'),
('ko', 'vendor.verified', '검증된 판매자', 'vendor'),
('ko', 'vendor.trust_score', '신뢰 점수', 'vendor'),
('ko', 'product.add_to_wishlist', '위시리스트에 추가', 'product'),
('ko', 'product.buy_now', '지금 구매', 'product'),
('ko', 'product.out_of_stock', '품절', 'product'),
('ko', 'featured_vendors.title', '추천 판매자', 'featured_vendors'),
('ko', 'featured_vendors.subtitle', '입증된 실적과 높은 신뢰 점수를 가진 최고 평점의 검증된 판매자들을 만나보세요. 모든 판매자가 귀하의 보호를 위해 연간 $250의 보증금을 예치했습니다.', 'featured_vendors'),
('ko', 'featured_vendors.view_all', '모든 검증된 판매자 보기', 'featured_vendors'),
('ko', 'common.loading', '로딩 중...', 'common'),
('ko', 'common.error', '오류', 'common'),
('ko', 'common.success', '성공', 'common'),
('ko', 'common.cancel', '취소', 'common'),
('ko', 'common.save', '저장', 'common'),
('ko', 'common.delete', '삭제', 'common'),
('ko', 'common.edit', '편집', 'common'),
('ko', 'common.search', '검색', 'common'),
('ko', 'common.filter', '필터', 'common')

ON CONFLICT (language_code, translation_key, context) DO NOTHING;