-- Add sample translations for testing
INSERT INTO public.translations (language_code, translation_key, translation_value, context) VALUES
('en', 'nav.home', 'Home', 'navigation'),
('en', 'nav.products', 'Products', 'navigation'), 
('en', 'nav.vendors', 'Vendors', 'navigation'),
('en', 'nav.forum', 'Forum', 'navigation'),
('en', 'marketplace.title', 'AI-Powered Anonymous Marketplace', 'homepage'),
('en', 'marketplace.subtitle', 'Trade securely with Bitcoin-only transactions, verified vendors, and AI-driven trust scoring.', 'homepage'),
('en', 'common.loading', 'Loading...', 'common'),
('en', 'common.error', 'Error', 'common'),
('en', 'common.success', 'Success', 'common'),
('es', 'nav.home', 'Inicio', 'navigation'),
('es', 'nav.products', 'Productos', 'navigation'),
('es', 'nav.vendors', 'Vendedores', 'navigation'), 
('es', 'nav.forum', 'Foro', 'navigation'),
('es', 'marketplace.title', 'Mercado Anónimo Impulsado por IA', 'homepage'),
('es', 'marketplace.subtitle', 'Comercia de forma segura con transacciones solo en Bitcoin, vendedores verificados y puntuación de confianza impulsada por IA.', 'homepage'),
('es', 'common.loading', 'Cargando...', 'common'),
('es', 'common.error', 'Error', 'common'),
('es', 'common.success', 'Éxito', 'common'),
('fr', 'nav.home', 'Accueil', 'navigation'),
('fr', 'nav.products', 'Produits', 'navigation'),
('fr', 'nav.vendors', 'Vendeurs', 'navigation'),
('fr', 'nav.forum', 'Forum', 'navigation'),
('fr', 'marketplace.title', 'Marché Anonyme Alimenté par IA', 'homepage'),
('fr', 'marketplace.subtitle', 'Échangez en toute sécurité avec des transactions uniquement en Bitcoin, des vendeurs vérifiés et un score de confiance piloté par IA.', 'homepage'),
('fr', 'common.loading', 'Chargement...', 'common'),
('fr', 'common.error', 'Erreur', 'common'),
('fr', 'common.success', 'Succès', 'common')
ON CONFLICT (language_code, translation_key, context) DO NOTHING;