// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkdhsqndcvwbglbtrgbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrZGhzcW5kY3Z3YmdsYnRyZ2J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NjIwMDEsImV4cCI6MjA2NzMzODAwMX0.jqO2_cen3Mbs-eOs_AHq6Yr-hCRSQwFcI9qAmp5hcG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});